-- | DOM names of row labels. Generated by `scripts/gen-dom.mjs`.
module Solid.Internal.Names where

import Data.String (toLower)

attributeName :: String -> String
attributeName = case _ of
  "acceptCharset" -> "accept-charset"
  "clipPath" -> "clip-path"
  "clipRule" -> "clip-rule"
  "dominantBaseline" -> "dominant-baseline"
  "fillOpacity" -> "fill-opacity"
  "fillRule" -> "fill-rule"
  "fontFamily" -> "font-family"
  "fontSize" -> "font-size"
  "fontWeight" -> "font-weight"
  "gradientTransform" -> "gradientTransform"
  "gradientUnits" -> "gradientUnits"
  "httpEquiv" -> "http-equiv"
  "markerEnd" -> "marker-end"
  "markerMid" -> "marker-mid"
  "markerStart" -> "marker-start"
  "pathLength" -> "pathLength"
  "patternUnits" -> "patternUnits"
  "pointerEvents" -> "pointer-events"
  "preserveAspectRatio" -> "preserveAspectRatio"
  "stopColor" -> "stop-color"
  "stopOpacity" -> "stop-opacity"
  "strokeDasharray" -> "stroke-dasharray"
  "strokeDashoffset" -> "stroke-dashoffset"
  "strokeLinecap" -> "stroke-linecap"
  "strokeLinejoin" -> "stroke-linejoin"
  "strokeOpacity" -> "stroke-opacity"
  "strokeWidth" -> "stroke-width"
  "textAnchor" -> "text-anchor"
  "vectorEffect" -> "vector-effect"
  "viewBox" -> "viewBox"
  label -> toLower label

eventName :: String -> String
eventName = case _ of
  "onDoubleClick" -> "onDblClick"
  label -> label
