-- | SVG presentation attributes. Generated by `scripts/gen-dom.mjs`.
module Solid.DOM.SVG.Props where

import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, bindingProp)

clipPath :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (clipPath :: a | r)
clipPath = bindingProp "clip-path" toAttrValue

clipRule :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (clipRule :: a | r)
clipRule = bindingProp "clip-rule" toAttrValue

cx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cx :: a | r)
cx = bindingProp "cx" toAttrValue

cy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cy :: a | r)
cy = bindingProp "cy" toAttrValue

d :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (d :: a | r)
d = bindingProp "d" toAttrValue

display :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (display :: a | r)
display = bindingProp "display" toAttrValue

dominantBaseline :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dominantBaseline :: a | r)
dominantBaseline = bindingProp "dominant-baseline" toAttrValue

dx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dx :: a | r)
dx = bindingProp "dx" toAttrValue

dy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dy :: a | r)
dy = bindingProp "dy" toAttrValue

fill :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fill :: a | r)
fill = bindingProp "fill" toAttrValue

fillOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fillOpacity :: a | r)
fillOpacity = bindingProp "fill-opacity" toAttrValue

fillRule :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fillRule :: a | r)
fillRule = bindingProp "fill-rule" toAttrValue

filter :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (filter :: a | r)
filter = bindingProp "filter" toAttrValue

fontFamily :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontFamily :: a | r)
fontFamily = bindingProp "font-family" toAttrValue

fontSize :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontSize :: a | r)
fontSize = bindingProp "font-size" toAttrValue

fontWeight :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontWeight :: a | r)
fontWeight = bindingProp "font-weight" toAttrValue

fx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fx :: a | r)
fx = bindingProp "fx" toAttrValue

fy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fy :: a | r)
fy = bindingProp "fy" toAttrValue

gradientTransform :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (gradientTransform :: a | r)
gradientTransform = bindingProp "gradientTransform" toAttrValue

gradientUnits :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (gradientUnits :: a | r)
gradientUnits = bindingProp "gradientUnits" toAttrValue

markerEnd :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerEnd :: a | r)
markerEnd = bindingProp "marker-end" toAttrValue

markerMid :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerMid :: a | r)
markerMid = bindingProp "marker-mid" toAttrValue

markerStart :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerStart :: a | r)
markerStart = bindingProp "marker-start" toAttrValue

mask :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (mask :: a | r)
mask = bindingProp "mask" toAttrValue

offset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (offset :: a | r)
offset = bindingProp "offset" toAttrValue

opacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (opacity :: a | r)
opacity = bindingProp "opacity" toAttrValue

pathLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pathLength :: a | r)
pathLength = bindingProp "pathLength" toAttrValue

patternUnits :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (patternUnits :: a | r)
patternUnits = bindingProp "patternUnits" toAttrValue

pointerEvents :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pointerEvents :: a | r)
pointerEvents = bindingProp "pointer-events" toAttrValue

points :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (points :: a | r)
points = bindingProp "points" toAttrValue

preserveAspectRatio :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (preserveAspectRatio :: a | r)
preserveAspectRatio = bindingProp "preserveAspectRatio" toAttrValue

r :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (r :: a | r)
r = bindingProp "r" toAttrValue

rx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rx :: a | r)
rx = bindingProp "rx" toAttrValue

ry :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (ry :: a | r)
ry = bindingProp "ry" toAttrValue

stopColor :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stopColor :: a | r)
stopColor = bindingProp "stop-color" toAttrValue

stopOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stopOpacity :: a | r)
stopOpacity = bindingProp "stop-opacity" toAttrValue

stroke :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stroke :: a | r)
stroke = bindingProp "stroke" toAttrValue

strokeDasharray :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeDasharray :: a | r)
strokeDasharray = bindingProp "stroke-dasharray" toAttrValue

strokeDashoffset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeDashoffset :: a | r)
strokeDashoffset = bindingProp "stroke-dashoffset" toAttrValue

strokeLinecap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeLinecap :: a | r)
strokeLinecap = bindingProp "stroke-linecap" toAttrValue

strokeLinejoin :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeLinejoin :: a | r)
strokeLinejoin = bindingProp "stroke-linejoin" toAttrValue

strokeOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeOpacity :: a | r)
strokeOpacity = bindingProp "stroke-opacity" toAttrValue

strokeWidth :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeWidth :: a | r)
strokeWidth = bindingProp "stroke-width" toAttrValue

textAnchor :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (textAnchor :: a | r)
textAnchor = bindingProp "text-anchor" toAttrValue

transform :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (transform :: a | r)
transform = bindingProp "transform" toAttrValue

vectorEffect :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (vectorEffect :: a | r)
vectorEffect = bindingProp "vector-effect" toAttrValue

viewBox :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (viewBox :: a | r)
viewBox = bindingProp "viewBox" toAttrValue

visibility :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (visibility :: a | r)
visibility = bindingProp "visibility" toAttrValue

x :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x :: a | r)
x = bindingProp "x" toAttrValue

x1 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x1 :: a | r)
x1 = bindingProp "x1" toAttrValue

x2 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x2 :: a | r)
x2 = bindingProp "x2" toAttrValue

y :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y :: a | r)
y = bindingProp "y" toAttrValue

y1 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y1 :: a | r)
y1 = bindingProp "y1" toAttrValue

y2 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y2 :: a | r)
y2 = bindingProp "y2" toAttrValue
