-- | SVG presentation attributes. Values may be fixed or `Accessor`s.
-- |
-- | Generated by `scripts/gen-dom.mjs` from `dom-indexed`; do not edit.
module Solid.DOM.SVG.Props
  ( clipPath
  , clipRule
  , cx
  , cy
  , d
  , display
  , dominantBaseline
  , dx
  , dy
  , fill
  , fillOpacity
  , fillRule
  , filter
  , fontFamily
  , fontSize
  , fontWeight
  , fx
  , fy
  , gradientTransform
  , gradientUnits
  , markerEnd
  , markerMid
  , markerStart
  , mask
  , offset
  , opacity
  , pathLength
  , patternUnits
  , pointerEvents
  , points
  , preserveAspectRatio
  , r
  , rx
  , ry
  , stopColor
  , stopOpacity
  , stroke
  , strokeDasharray
  , strokeDashoffset
  , strokeLinecap
  , strokeLinejoin
  , strokeOpacity
  , strokeWidth
  , textAnchor
  , transform
  , vectorEffect
  , viewBox
  , visibility
  , x
  , x1
  , x2
  , y
  , y1
  , y2
  ) where

import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, binding, bindingProp)

clipPath :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (clipPath :: a | r)
clipPath v = bindingProp "clip-path" toAttrValue (binding v)

clipRule :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (clipRule :: a | r)
clipRule v = bindingProp "clip-rule" toAttrValue (binding v)

cx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cx :: a | r)
cx v = bindingProp "cx" toAttrValue (binding v)

cy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cy :: a | r)
cy v = bindingProp "cy" toAttrValue (binding v)

d :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (d :: a | r)
d v = bindingProp "d" toAttrValue (binding v)

display :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (display :: a | r)
display v = bindingProp "display" toAttrValue (binding v)

dominantBaseline :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dominantBaseline :: a | r)
dominantBaseline v = bindingProp "dominant-baseline" toAttrValue (binding v)

dx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dx :: a | r)
dx v = bindingProp "dx" toAttrValue (binding v)

dy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dy :: a | r)
dy v = bindingProp "dy" toAttrValue (binding v)

fill :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fill :: a | r)
fill v = bindingProp "fill" toAttrValue (binding v)

fillOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fillOpacity :: a | r)
fillOpacity v = bindingProp "fill-opacity" toAttrValue (binding v)

fillRule :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fillRule :: a | r)
fillRule v = bindingProp "fill-rule" toAttrValue (binding v)

filter :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (filter :: a | r)
filter v = bindingProp "filter" toAttrValue (binding v)

fontFamily :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontFamily :: a | r)
fontFamily v = bindingProp "font-family" toAttrValue (binding v)

fontSize :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontSize :: a | r)
fontSize v = bindingProp "font-size" toAttrValue (binding v)

fontWeight :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontWeight :: a | r)
fontWeight v = bindingProp "font-weight" toAttrValue (binding v)

fx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fx :: a | r)
fx v = bindingProp "fx" toAttrValue (binding v)

fy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fy :: a | r)
fy v = bindingProp "fy" toAttrValue (binding v)

gradientTransform :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (gradientTransform :: a | r)
gradientTransform v = bindingProp "gradientTransform" toAttrValue (binding v)

gradientUnits :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (gradientUnits :: a | r)
gradientUnits v = bindingProp "gradientUnits" toAttrValue (binding v)

markerEnd :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerEnd :: a | r)
markerEnd v = bindingProp "marker-end" toAttrValue (binding v)

markerMid :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerMid :: a | r)
markerMid v = bindingProp "marker-mid" toAttrValue (binding v)

markerStart :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerStart :: a | r)
markerStart v = bindingProp "marker-start" toAttrValue (binding v)

mask :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (mask :: a | r)
mask v = bindingProp "mask" toAttrValue (binding v)

offset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (offset :: a | r)
offset v = bindingProp "offset" toAttrValue (binding v)

opacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (opacity :: a | r)
opacity v = bindingProp "opacity" toAttrValue (binding v)

pathLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pathLength :: a | r)
pathLength v = bindingProp "pathLength" toAttrValue (binding v)

patternUnits :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (patternUnits :: a | r)
patternUnits v = bindingProp "patternUnits" toAttrValue (binding v)

pointerEvents :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pointerEvents :: a | r)
pointerEvents v = bindingProp "pointer-events" toAttrValue (binding v)

points :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (points :: a | r)
points v = bindingProp "points" toAttrValue (binding v)

preserveAspectRatio :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (preserveAspectRatio :: a | r)
preserveAspectRatio v = bindingProp "preserveAspectRatio" toAttrValue (binding v)

r :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (r :: a | r)
r v = bindingProp "r" toAttrValue (binding v)

rx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rx :: a | r)
rx v = bindingProp "rx" toAttrValue (binding v)

ry :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (ry :: a | r)
ry v = bindingProp "ry" toAttrValue (binding v)

stopColor :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stopColor :: a | r)
stopColor v = bindingProp "stop-color" toAttrValue (binding v)

stopOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stopOpacity :: a | r)
stopOpacity v = bindingProp "stop-opacity" toAttrValue (binding v)

stroke :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stroke :: a | r)
stroke v = bindingProp "stroke" toAttrValue (binding v)

strokeDasharray :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeDasharray :: a | r)
strokeDasharray v = bindingProp "stroke-dasharray" toAttrValue (binding v)

strokeDashoffset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeDashoffset :: a | r)
strokeDashoffset v = bindingProp "stroke-dashoffset" toAttrValue (binding v)

strokeLinecap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeLinecap :: a | r)
strokeLinecap v = bindingProp "stroke-linecap" toAttrValue (binding v)

strokeLinejoin :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeLinejoin :: a | r)
strokeLinejoin v = bindingProp "stroke-linejoin" toAttrValue (binding v)

strokeOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeOpacity :: a | r)
strokeOpacity v = bindingProp "stroke-opacity" toAttrValue (binding v)

strokeWidth :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeWidth :: a | r)
strokeWidth v = bindingProp "stroke-width" toAttrValue (binding v)

textAnchor :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (textAnchor :: a | r)
textAnchor v = bindingProp "text-anchor" toAttrValue (binding v)

transform :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (transform :: a | r)
transform v = bindingProp "transform" toAttrValue (binding v)

vectorEffect :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (vectorEffect :: a | r)
vectorEffect v = bindingProp "vector-effect" toAttrValue (binding v)

viewBox :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (viewBox :: a | r)
viewBox v = bindingProp "viewBox" toAttrValue (binding v)

visibility :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (visibility :: a | r)
visibility v = bindingProp "visibility" toAttrValue (binding v)

x :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x :: a | r)
x v = bindingProp "x" toAttrValue (binding v)

x1 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x1 :: a | r)
x1 v = bindingProp "x1" toAttrValue (binding v)

x2 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x2 :: a | r)
x2 v = bindingProp "x2" toAttrValue (binding v)

y :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y :: a | r)
y v = bindingProp "y" toAttrValue (binding v)

y1 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y1 :: a | r)
y1 v = bindingProp "y1" toAttrValue (binding v)

y2 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y2 :: a | r)
y2 v = bindingProp "y2" toAttrValue (binding v)
