-- | SVG presentation attributes. Values may be fixed or `Accessor`s.
-- |
-- | Generated by `scripts/gen-dom.mjs` from `dom-indexed`; do not edit.
module Solid.DOM.SVG.Props
  ( clipPath
  , clipRule
  , cx
  , cy
  , d
  , display
  , dominantBaseline
  , dx
  , dy
  , fill
  , fillOpacity
  , fillRule
  , filter
  , fontFamily
  , fontSize
  , fontWeight
  , fx
  , fy
  , gradientTransform
  , gradientUnits
  , markerEnd
  , markerMid
  , markerStart
  , mask
  , offset
  , opacity
  , pathLength
  , patternUnits
  , pointerEvents
  , points
  , preserveAspectRatio
  , r
  , rx
  , ry
  , stopColor
  , stopOpacity
  , stroke
  , strokeDasharray
  , strokeDashoffset
  , strokeLinecap
  , strokeLinejoin
  , strokeOpacity
  , strokeWidth
  , textAnchor
  , transform
  , vectorEffect
  , viewBox
  , visibility
  , x
  , x1
  , x2
  , y
  , y1
  , y2
  ) where

import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, binding, bindingProp)

clipPath :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (clipPath :: a | r)
clipPath value = bindingProp "clip-path" toAttrValue (binding value)

clipRule :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (clipRule :: a | r)
clipRule value = bindingProp "clip-rule" toAttrValue (binding value)

cx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cx :: a | r)
cx value = bindingProp "cx" toAttrValue (binding value)

cy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cy :: a | r)
cy value = bindingProp "cy" toAttrValue (binding value)

d :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (d :: a | r)
d value = bindingProp "d" toAttrValue (binding value)

display :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (display :: a | r)
display value = bindingProp "display" toAttrValue (binding value)

dominantBaseline :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dominantBaseline :: a | r)
dominantBaseline value = bindingProp "dominant-baseline" toAttrValue (binding value)

dx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dx :: a | r)
dx value = bindingProp "dx" toAttrValue (binding value)

dy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dy :: a | r)
dy value = bindingProp "dy" toAttrValue (binding value)

fill :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fill :: a | r)
fill value = bindingProp "fill" toAttrValue (binding value)

fillOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fillOpacity :: a | r)
fillOpacity value = bindingProp "fill-opacity" toAttrValue (binding value)

fillRule :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fillRule :: a | r)
fillRule value = bindingProp "fill-rule" toAttrValue (binding value)

filter :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (filter :: a | r)
filter value = bindingProp "filter" toAttrValue (binding value)

fontFamily :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontFamily :: a | r)
fontFamily value = bindingProp "font-family" toAttrValue (binding value)

fontSize :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontSize :: a | r)
fontSize value = bindingProp "font-size" toAttrValue (binding value)

fontWeight :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fontWeight :: a | r)
fontWeight value = bindingProp "font-weight" toAttrValue (binding value)

fx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fx :: a | r)
fx value = bindingProp "fx" toAttrValue (binding value)

fy :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (fy :: a | r)
fy value = bindingProp "fy" toAttrValue (binding value)

gradientTransform :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (gradientTransform :: a | r)
gradientTransform value = bindingProp "gradientTransform" toAttrValue (binding value)

gradientUnits :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (gradientUnits :: a | r)
gradientUnits value = bindingProp "gradientUnits" toAttrValue (binding value)

markerEnd :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerEnd :: a | r)
markerEnd value = bindingProp "marker-end" toAttrValue (binding value)

markerMid :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerMid :: a | r)
markerMid value = bindingProp "marker-mid" toAttrValue (binding value)

markerStart :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (markerStart :: a | r)
markerStart value = bindingProp "marker-start" toAttrValue (binding value)

mask :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (mask :: a | r)
mask value = bindingProp "mask" toAttrValue (binding value)

offset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (offset :: a | r)
offset value = bindingProp "offset" toAttrValue (binding value)

opacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (opacity :: a | r)
opacity value = bindingProp "opacity" toAttrValue (binding value)

pathLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pathLength :: a | r)
pathLength value = bindingProp "pathLength" toAttrValue (binding value)

patternUnits :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (patternUnits :: a | r)
patternUnits value = bindingProp "patternUnits" toAttrValue (binding value)

pointerEvents :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pointerEvents :: a | r)
pointerEvents value = bindingProp "pointer-events" toAttrValue (binding value)

points :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (points :: a | r)
points value = bindingProp "points" toAttrValue (binding value)

preserveAspectRatio :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (preserveAspectRatio :: a | r)
preserveAspectRatio value = bindingProp "preserveAspectRatio" toAttrValue (binding value)

r :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (r :: a | r)
r value = bindingProp "r" toAttrValue (binding value)

rx :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rx :: a | r)
rx value = bindingProp "rx" toAttrValue (binding value)

ry :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (ry :: a | r)
ry value = bindingProp "ry" toAttrValue (binding value)

stopColor :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stopColor :: a | r)
stopColor value = bindingProp "stop-color" toAttrValue (binding value)

stopOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stopOpacity :: a | r)
stopOpacity value = bindingProp "stop-opacity" toAttrValue (binding value)

stroke :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (stroke :: a | r)
stroke value = bindingProp "stroke" toAttrValue (binding value)

strokeDasharray :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeDasharray :: a | r)
strokeDasharray value = bindingProp "stroke-dasharray" toAttrValue (binding value)

strokeDashoffset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeDashoffset :: a | r)
strokeDashoffset value = bindingProp "stroke-dashoffset" toAttrValue (binding value)

strokeLinecap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeLinecap :: a | r)
strokeLinecap value = bindingProp "stroke-linecap" toAttrValue (binding value)

strokeLinejoin :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeLinejoin :: a | r)
strokeLinejoin value = bindingProp "stroke-linejoin" toAttrValue (binding value)

strokeOpacity :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeOpacity :: a | r)
strokeOpacity value = bindingProp "stroke-opacity" toAttrValue (binding value)

strokeWidth :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (strokeWidth :: a | r)
strokeWidth value = bindingProp "stroke-width" toAttrValue (binding value)

textAnchor :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (textAnchor :: a | r)
textAnchor value = bindingProp "text-anchor" toAttrValue (binding value)

transform :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (transform :: a | r)
transform value = bindingProp "transform" toAttrValue (binding value)

vectorEffect :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (vectorEffect :: a | r)
vectorEffect value = bindingProp "vector-effect" toAttrValue (binding value)

viewBox :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (viewBox :: a | r)
viewBox value = bindingProp "viewBox" toAttrValue (binding value)

visibility :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (visibility :: a | r)
visibility value = bindingProp "visibility" toAttrValue (binding value)

x :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x :: a | r)
x value = bindingProp "x" toAttrValue (binding value)

x1 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x1 :: a | r)
x1 value = bindingProp "x1" toAttrValue (binding value)

x2 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (x2 :: a | r)
x2 value = bindingProp "x2" toAttrValue (binding value)

y :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y :: a | r)
y value = bindingProp "y" toAttrValue (binding value)

y1 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y1 :: a | r)
y1 value = bindingProp "y1" toAttrValue (binding value)

y2 :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (y2 :: a | r)
y2 value = bindingProp "y2" toAttrValue (binding value)
