// Generates Solid.DOM.HTML, Solid.DOM.Props, Solid.DOM.SVG and
// Solid.DOM.SVG.Props from the element rows in `dom-indexed`.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const packages = join(root, ".spago", "p");
const domIndexedDir = readdirSync(packages).find((name) => name.startsWith("dom-indexed-"));
if (!domIndexedDir) throw new Error("dom-indexed not found in .spago/p; run `spago install` first");

const indexed = readFileSync(join(packages, domIndexedDir, "src", "DOM", "HTML", "Indexed.purs"), "utf8");

const reserved = new Set([
  "ado", "case", "class", "data", "derive", "do", "else", "false", "forall", "foreign", "if", "import",
  "in", "infix", "infixl", "infixr", "instance", "let", "module", "newtype", "of", "then", "true", "type", "where",
]);
const identifier = (name) => (reserved.has(name) ? `${name}_` : name);

const voidElements = new Set([
  "area", "base", "br", "col", "command", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr",
]);

const extraElements = ["picture", "search", "slot", "template"];

const elements = [...indexed.matchAll(/^type HTML([a-z0-9]+)\b/gm)].map((match) => match[1]);

const labels = new Map();
for (const match of indexed.matchAll(/[(,]\s*([a-z][A-Za-z0-9]*) :: ([A-Z][A-Za-z]*)/g)) {
  const [, label, type] = match;
  if (!labels.has(label)) labels.set(label, new Set());
  labels.get(label).add(type);
}

const isEvent = (label) => /^on[A-Z]/.test(label);

const attributeName = (label) =>
  ({ acceptCharset: "accept-charset", httpEquiv: "http-equiv" })[label] ?? label.toLowerCase();

const eventName = (label) => ({ onDoubleClick: "onDblClick" })[label] ?? label;

const header = (name, doc) => `-- | ${doc} Generated by \`scripts/gen-dom.mjs\`.\nmodule ${name} where\n`;

const allElements = [...elements, ...extraElements].sort();
const htmlRow = (el) => (extraElements.includes(el) ? "(I.Interactive ())" : `I.HTML${el}`);

const htmlBody = allElements
  .map((el) => {
    const name = identifier(el);
    const row = htmlRow(el);
    if (voidElements.has(el)) {
      return [
        `${name} :: Array (Prop ${row}) -> JSX`,
        `${name} props = elementWith HtmlNamespace "${el}" props []`,
        ``,
        `${el}_ :: JSX`,
        `${el}_ = elementWith HtmlNamespace "${el}" [] []`,
      ].join("\n");
    }
    return [
      `${name} :: Array (Prop ${row}) -> Array JSX -> JSX`,
      `${name} = elementWith HtmlNamespace "${el}"`,
      ``,
      `${el}_ :: Array JSX -> JSX`,
      `${el}_ = elementWith HtmlNamespace "${el}" []`,
    ].join("\n");
  })
  .join("\n\n");

const html = `${header("Solid.DOM.HTML", "HTML elements, typed by the attributes and events each one supports.")}
import DOM.HTML.Indexed as I
import Solid.Internal.View (JSX, Namespace(..), Prop, elementWith)

${htmlBody}
`;

const propLabels = [...labels.keys()].sort();

const propBody = propLabels
  .map((label) => {
    const name = identifier(label);
    const types = [...labels.get(label)];
    if (isEvent(label)) {
      const eventType = types.length === 1 ? types[0] : null;
      if (eventType === null) {
        return [
          `${name} :: forall r e. (e -> Effect Unit) -> Prop (${label} :: e | r)`,
          `${name} = eventProp "${eventName(label)}"`,
        ].join("\n");
      }
      return [
        `${name} :: forall r. (${eventType} -> Effect Unit) -> Prop (${label} :: ${eventType} | r)`,
        `${name} = eventProp "${eventName(label)}"`,
      ].join("\n");
    }
    return [
      `${name} :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (${label} :: a | r)`,
      `${name} v = bindingProp "${attributeName(label)}" toAttrValue (binding v)`,
    ].join("\n");
  })
  .join("\n\n");

const eventTypes = new Set(propLabels.filter(isEvent).flatMap((label) => [...labels.get(label)]));
const eventImports = {
  ClipboardEvent: "import Web.Clipboard.ClipboardEvent (ClipboardEvent)",
  DragEvent: "import Web.HTML.Event.DragEvent (DragEvent)",
  Event: "import Web.Event.Event (Event)",
  FocusEvent: "import Web.UIEvent.FocusEvent (FocusEvent)",
  KeyboardEvent: "import Web.UIEvent.KeyboardEvent (KeyboardEvent)",
  MouseEvent: "import Web.UIEvent.MouseEvent (MouseEvent)",
  PointerEvent: "import Web.PointerEvent (PointerEvent)",
  TouchEvent: "import Web.TouchEvent (TouchEvent)",
  WheelEvent: "import Web.UIEvent.WheelEvent (WheelEvent)",
};
for (const type of eventTypes) {
  if (!eventImports[type]) throw new Error(`No import known for event type ${type}`);
}

const props = `${header("Solid.DOM.Props", "Element properties, each usable only on elements that support it.")}
import Prelude

${[...eventTypes].sort().map((type) => eventImports[type]).join("\n")}
import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, binding, bindingProp, eventProp)
import Effect (Effect)

${propBody}
`;

writeFileSync(join(root, "src", "Solid", "DOM", "HTML.purs"), html);
writeFileSync(join(root, "src", "Solid", "DOM", "Props.purs"), props);
console.log(`[gen-dom] ${allElements.length} elements, ${propLabels.length} props`);

// dom-indexed has no SVG rows, so SVG elements share one row.

const svgElements = (
  "a altGlyph altGlyphDef altGlyphItem animate animateColor animateMotion animateTransform circle clipPath " +
  "colorProfile cursor defs desc ellipse feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix " +
  "feDiffuseLighting feDisplacementMap feDistantLight feDropShadow feFlood feFuncA feFuncB feFuncG feFuncR " +
  "feGaussianBlur feImage feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight " +
  "feTile feTurbulence filter font foreignObject g glyph glyphRef hkern image line linearGradient marker mask " +
  "metadata missingGlyph mpath path pattern polygon polyline radialGradient rect script set stop style svg " +
  "switch symbol text textPath title tref tspan use view vkern"
).split(" ");

const svgAttributes = {
  clipPath: "clip-path", clipRule: "clip-rule", cx: "cx", cy: "cy", d: "d", display: "display",
  dominantBaseline: "dominant-baseline", dx: "dx", dy: "dy", fill: "fill", fillOpacity: "fill-opacity",
  fillRule: "fill-rule", filter: "filter", fontFamily: "font-family", fontSize: "font-size", fontWeight: "font-weight",
  fx: "fx", fy: "fy", gradientTransform: "gradientTransform", gradientUnits: "gradientUnits", markerEnd: "marker-end",
  markerMid: "marker-mid", markerStart: "marker-start", mask: "mask", offset: "offset", opacity: "opacity",
  pathLength: "pathLength", patternUnits: "patternUnits", pointerEvents: "pointer-events", points: "points",
  preserveAspectRatio: "preserveAspectRatio", r: "r", rx: "rx", ry: "ry", stopColor: "stop-color",
  stopOpacity: "stop-opacity", stroke: "stroke", strokeDasharray: "stroke-dasharray",
  strokeDashoffset: "stroke-dashoffset", strokeLinecap: "stroke-linecap", strokeLinejoin: "stroke-linejoin",
  strokeOpacity: "stroke-opacity", strokeWidth: "stroke-width", textAnchor: "text-anchor", transform: "transform",
  vectorEffect: "vector-effect", viewBox: "viewBox", visibility: "visibility", x: "x", x1: "x1", x2: "x2", y: "y",
  y1: "y1", y2: "y2",
};

const svgShared = ["class :: String", "height :: String", "href :: String", "id :: String", "lang :: String",
  "style :: String", "tabIndex :: Int", "width :: String"];

const svgRow = [
  ...svgShared,
  ...Object.keys(svgAttributes).map((label) => `${label} :: String`),
];

const svgNames = svgElements.map((el) => ({ el, name: identifier(el) }));

const svg = `${header("Solid.DOM.SVG", "SVG elements.")}
import DOM.HTML.Indexed as I
import Solid.Internal.View (JSX, Namespace(..), Prop, elementWith)

type SVGAttributes = I.InteractiveEvents
  ( ${svgRow.join("\n  , ")}
  )

${svgNames
  .map(({ el, name }) =>
    [
      `${name} :: Array (Prop SVGAttributes) -> Array JSX -> JSX`,
      `${name} = elementWith SvgNamespace "${el}"`,
      ``,
      `${el}_ :: Array JSX -> JSX`,
      `${el}_ = elementWith SvgNamespace "${el}" []`,
    ].join("\n")
  )
  .join("\n\n")}
`;

const svgPropLabels = Object.keys(svgAttributes).sort();
const svgProps = `${header("Solid.DOM.SVG.Props", "SVG presentation attributes.")}
import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, binding, bindingProp)

${svgPropLabels
  .map((label) =>
    [
      `${identifier(label)} :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (${label} :: a | r)`,
      `${identifier(label)} v = bindingProp "${svgAttributes[label]}" toAttrValue (binding v)`,
    ].join("\n")
  )
  .join("\n\n")}
`;

writeFileSync(join(root, "src", "Solid", "DOM", "SVG.purs"), svg);
writeFileSync(join(root, "src", "Solid", "DOM", "SVG", "Props.purs"), svgProps);
console.log(`[gen-dom] ${svgElements.length} SVG elements, ${svgPropLabels.length} SVG props`);
