// Generates Solid.DOM.HTML, Solid.DOM.SVG and Solid.Internal.Names
// from the element rows in `dom-indexed`.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const packages = join(root, ".spago", "p");
const domIndexedDir = readdirSync(packages).find((name) => name.startsWith("dom-indexed-"));
if (!domIndexedDir) throw new Error("dom-indexed not found in .spago/p; run `spago install` first");

const indexed = readFileSync(join(packages, domIndexedDir, "src", "DOM", "HTML", "Indexed.purs"), "utf8");

const webHtmlDir = readdirSync(packages).find((name) => name.startsWith("web-html-"));
if (!webHtmlDir) throw new Error("web-html not found in .spago/p; run `spago install` first");
const elementTypes = new Set(
  readdirSync(join(packages, webHtmlDir, "src", "Web", "HTML"))
    .filter((file) => /^HTML\w+Element\.purs$/.test(file))
    .map((file) => file.slice(0, -5))
);

const reserved = new Set([
  "ado", "case", "class", "data", "derive", "do", "else", "false", "forall", "foreign", "if", "import",
  "in", "infix", "infixl", "infixr", "instance", "let", "module", "newtype", "of", "then", "true", "type", "where",
]);
const identifier = (name) => (reserved.has(name) ? `${name}_` : name);

const voidElements = new Set([
  "area", "base", "br", "col", "command", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr",
]);

const extraElements = ["picture", "search", "slot", "template"];

const elements = [...indexed.matchAll(/^type HTML([a-z0-9]+)\b/gm)].map((match) => match[1]);

const header = (name, doc) => `-- | ${doc} Generated by \`scripts/gen-dom.mjs\`.\nmodule ${name} where\n`;

const allElements = [...elements, ...extraElements].sort();

// Each row also carries the element's DOM type under "$element", for `ref`.
const elementTypeNames = {
  a: "Anchor", blockquote: "Quote", br: "BR", caption: "TableCaption", col: "TableCol", colgroup: "TableCol",
  datalist: "DataList", del: "Mod", dl: "DList", fieldset: "FieldSet", h1: "Heading", h2: "Heading", h3: "Heading",
  h4: "Heading", h5: "Heading", h6: "Heading", hr: "HR", iframe: "IFrame", img: "Image", ins: "Mod", li: "LI",
  ol: "OList", optgroup: "OptGroup", p: "Paragraph", q: "Quote", tbody: "TableSection", td: "TableDataCell",
  textarea: "TextArea", tfoot: "TableSection", th: "TableHeaderCell", thead: "TableSection", tr: "TableRow",
  ul: "UList",
};
const elementType = (el) => {
  const type = `HTML${elementTypeNames[el] ?? el[0].toUpperCase() + el.slice(1)}Element`;
  return elementTypes.has(type) ? type : "HTMLElement";
};
const htmlRow = (el) =>
  `("$element" :: ${elementType(el)} | ${extraElements.includes(el) ? "I.Interactive ()" : `I.HTML${el}`})`;

const htmlBody = allElements
  .map((el) => {
    const name = identifier(el);
    const row = htmlRow(el);
    return voidElements.has(el)
      ? [
          `${name} :: forall props. Props ${row} props => Record props -> JSX`,
          `${name} = typedVoidElement @${row} htmlNamespace "${el}"`,
        ].join("\n")
      : [
          `${name} :: forall props children. Props ${row} props => Children children => Record props -> children -> JSX`,
          `${name} = typedElement @${row} htmlNamespace "${el}"`,
        ].join("\n");
  })
  .join("\n\n");

const html = `${header("Solid.DOM.HTML", "HTML elements, typed by the attributes and events each one supports.")}
import DOM.HTML.Indexed as I
import Solid.Internal.Props (class Children, class Props, typedElement, typedVoidElement)
import Solid.Internal.View (JSX, htmlNamespace)
${[...new Set(allElements.map(elementType))].sort().map((type) => `import Web.HTML.${type} (${type})`).join("\n")}

${htmlBody}
`;

writeFileSync(join(root, "src", "Solid", "DOM", "HTML.purs"), html);
console.log(`[gen-dom] ${allElements.length} elements`);

// dom-indexed has no SVG rows, so SVG elements share one row.

const svgElements = (
  "a altGlyph altGlyphDef altGlyphItem animate animateColor animateMotion animateTransform circle clipPath " +
  "colorProfile cursor defs desc ellipse feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix " +
  "feDiffuseLighting feDisplacementMap feDistantLight feDropShadow feFlood feFuncA feFuncB feFuncG feFuncR " +
  "feGaussianBlur feImage feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight " +
  "feTile feTurbulence filter font foreignObject g glyph glyphRef hkern image line linearGradient marker mask " +
  "metadata missingGlyph mpath path pattern polygon polyline radialGradient rect script set stop style svg " +
  "switch symbol text textPath title tref tspan use view vkern"
).split(" ");

const svgAttributes = {
  clipPath: "clip-path", clipRule: "clip-rule", cx: "cx", cy: "cy", d: "d", display: "display",
  dominantBaseline: "dominant-baseline", dx: "dx", dy: "dy", fill: "fill", fillOpacity: "fill-opacity",
  fillRule: "fill-rule", filter: "filter", fontFamily: "font-family", fontSize: "font-size", fontWeight: "font-weight",
  fx: "fx", fy: "fy", gradientTransform: "gradientTransform", gradientUnits: "gradientUnits", markerEnd: "marker-end",
  markerMid: "marker-mid", markerStart: "marker-start", mask: "mask", offset: "offset", opacity: "opacity",
  pathLength: "pathLength", patternUnits: "patternUnits", pointerEvents: "pointer-events", points: "points",
  preserveAspectRatio: "preserveAspectRatio", r: "r", rx: "rx", ry: "ry", stopColor: "stop-color",
  stopOpacity: "stop-opacity", stroke: "stroke", strokeDasharray: "stroke-dasharray",
  strokeDashoffset: "stroke-dashoffset", strokeLinecap: "stroke-linecap", strokeLinejoin: "stroke-linejoin",
  strokeOpacity: "stroke-opacity", strokeWidth: "stroke-width", textAnchor: "text-anchor", transform: "transform",
  vectorEffect: "vector-effect", viewBox: "viewBox", visibility: "visibility", x: "x", x1: "x1", x2: "x2", y: "y",
  y1: "y1", y2: "y2",
};

const svgShared = ['"$element" :: Element', "class :: String", "height :: String", "href :: String", "id :: String", "lang :: String",
  "style :: String", "tabIndex :: Int", "width :: String"];

const svgRow = [
  ...svgShared,
  ...Object.keys(svgAttributes).map((label) => `${label} :: String`),
];

const svgNames = svgElements.map((el) => ({ el, name: identifier(el) }));

const svg = `${header("Solid.DOM.SVG", "SVG elements.")}
import DOM.HTML.Indexed as I
import Solid.Internal.Props (class Children, class Props, typedElement)
import Solid.Internal.View (JSX, svgNamespace)
import Web.DOM.Element (Element)

type SVGAttributes = I.InteractiveEvents
  ( ${svgRow.join("\n  , ")}
  )

${svgNames
  .map(({ el, name }) =>
    [
      `${name} :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX`,
      `${name} = typedElement @SVGAttributes svgNamespace "${el}"`,
    ].join("\n")
  )
  .join("\n\n")}
`;

writeFileSync(join(root, "src", "Solid", "DOM", "SVG.purs"), svg);
console.log(`[gen-dom] ${svgElements.length} SVG elements`);

// Field labels whose DOM name isn't the label lowercased.
const htmlAttributes = { acceptCharset: "accept-charset", httpEquiv: "http-equiv" };
const renamed = Object.entries({ ...htmlAttributes, ...svgAttributes }).filter(([label, name]) => name !== label.toLowerCase());
for (const label of Object.keys(htmlAttributes)) {
  if (label in svgAttributes && svgAttributes[label] !== htmlAttributes[label]) throw new Error(`${label} is named differently in HTML and SVG`);
}

const names = `${header("Solid.Internal.Names", "DOM names of row labels.")}
import Data.String (toLower)

attributeName :: String -> String
attributeName = case _ of
${renamed.sort(([a], [b]) => (a < b ? -1 : 1)).map(([label, name]) => `  "${label}" -> "${name}"`).join("\n")}
  label -> toLower label

eventName :: String -> String
eventName = case _ of
  "onDoubleClick" -> "onDblClick"
  label -> label
`;

writeFileSync(join(root, "src", "Solid", "Internal", "Names.purs"), names);
