-- | HTML elements, typed by the attributes and events each one supports. Generated by `scripts/gen-dom.mjs`.
module Solid.DOM.HTML where

import DOM.HTML.Indexed as I
import Solid.Internal.Props (class Children, class Props, typedElement, typedVoidElement)
import Solid.Internal.View (JSX, htmlNamespace)
import Web.HTML.HTMLAnchorElement (HTMLAnchorElement)
import Web.HTML.HTMLAreaElement (HTMLAreaElement)
import Web.HTML.HTMLAudioElement (HTMLAudioElement)
import Web.HTML.HTMLBRElement (HTMLBRElement)
import Web.HTML.HTMLBaseElement (HTMLBaseElement)
import Web.HTML.HTMLBodyElement (HTMLBodyElement)
import Web.HTML.HTMLButtonElement (HTMLButtonElement)
import Web.HTML.HTMLCanvasElement (HTMLCanvasElement)
import Web.HTML.HTMLDListElement (HTMLDListElement)
import Web.HTML.HTMLDataListElement (HTMLDataListElement)
import Web.HTML.HTMLDialogElement (HTMLDialogElement)
import Web.HTML.HTMLDivElement (HTMLDivElement)
import Web.HTML.HTMLElement (HTMLElement)
import Web.HTML.HTMLEmbedElement (HTMLEmbedElement)
import Web.HTML.HTMLFieldSetElement (HTMLFieldSetElement)
import Web.HTML.HTMLFormElement (HTMLFormElement)
import Web.HTML.HTMLHRElement (HTMLHRElement)
import Web.HTML.HTMLHeadElement (HTMLHeadElement)
import Web.HTML.HTMLHeadingElement (HTMLHeadingElement)
import Web.HTML.HTMLHtmlElement (HTMLHtmlElement)
import Web.HTML.HTMLIFrameElement (HTMLIFrameElement)
import Web.HTML.HTMLImageElement (HTMLImageElement)
import Web.HTML.HTMLInputElement (HTMLInputElement)
import Web.HTML.HTMLLIElement (HTMLLIElement)
import Web.HTML.HTMLLabelElement (HTMLLabelElement)
import Web.HTML.HTMLLegendElement (HTMLLegendElement)
import Web.HTML.HTMLLinkElement (HTMLLinkElement)
import Web.HTML.HTMLMapElement (HTMLMapElement)
import Web.HTML.HTMLMetaElement (HTMLMetaElement)
import Web.HTML.HTMLMeterElement (HTMLMeterElement)
import Web.HTML.HTMLModElement (HTMLModElement)
import Web.HTML.HTMLOListElement (HTMLOListElement)
import Web.HTML.HTMLObjectElement (HTMLObjectElement)
import Web.HTML.HTMLOptGroupElement (HTMLOptGroupElement)
import Web.HTML.HTMLOptionElement (HTMLOptionElement)
import Web.HTML.HTMLOutputElement (HTMLOutputElement)
import Web.HTML.HTMLParagraphElement (HTMLParagraphElement)
import Web.HTML.HTMLParamElement (HTMLParamElement)
import Web.HTML.HTMLPreElement (HTMLPreElement)
import Web.HTML.HTMLProgressElement (HTMLProgressElement)
import Web.HTML.HTMLQuoteElement (HTMLQuoteElement)
import Web.HTML.HTMLScriptElement (HTMLScriptElement)
import Web.HTML.HTMLSelectElement (HTMLSelectElement)
import Web.HTML.HTMLSourceElement (HTMLSourceElement)
import Web.HTML.HTMLSpanElement (HTMLSpanElement)
import Web.HTML.HTMLStyleElement (HTMLStyleElement)
import Web.HTML.HTMLTableCaptionElement (HTMLTableCaptionElement)
import Web.HTML.HTMLTableColElement (HTMLTableColElement)
import Web.HTML.HTMLTableDataCellElement (HTMLTableDataCellElement)
import Web.HTML.HTMLTableElement (HTMLTableElement)
import Web.HTML.HTMLTableHeaderCellElement (HTMLTableHeaderCellElement)
import Web.HTML.HTMLTableRowElement (HTMLTableRowElement)
import Web.HTML.HTMLTableSectionElement (HTMLTableSectionElement)
import Web.HTML.HTMLTemplateElement (HTMLTemplateElement)
import Web.HTML.HTMLTextAreaElement (HTMLTextAreaElement)
import Web.HTML.HTMLTimeElement (HTMLTimeElement)
import Web.HTML.HTMLTitleElement (HTMLTitleElement)
import Web.HTML.HTMLTrackElement (HTMLTrackElement)
import Web.HTML.HTMLUListElement (HTMLUListElement)
import Web.HTML.HTMLVideoElement (HTMLVideoElement)

a :: forall props children. Props ("$element" :: HTMLAnchorElement | I.HTMLa) props => Children children => Record props -> children -> JSX
a = typedElement @("$element" :: HTMLAnchorElement | I.HTMLa) htmlNamespace "a"

abbr :: forall props children. Props ("$element" :: HTMLElement | I.HTMLabbr) props => Children children => Record props -> children -> JSX
abbr = typedElement @("$element" :: HTMLElement | I.HTMLabbr) htmlNamespace "abbr"

address :: forall props children. Props ("$element" :: HTMLElement | I.HTMLaddress) props => Children children => Record props -> children -> JSX
address = typedElement @("$element" :: HTMLElement | I.HTMLaddress) htmlNamespace "address"

area :: forall props. Props ("$element" :: HTMLAreaElement | I.HTMLarea) props => Record props -> JSX
area = typedVoidElement @("$element" :: HTMLAreaElement | I.HTMLarea) htmlNamespace "area"

article :: forall props children. Props ("$element" :: HTMLElement | I.HTMLarticle) props => Children children => Record props -> children -> JSX
article = typedElement @("$element" :: HTMLElement | I.HTMLarticle) htmlNamespace "article"

aside :: forall props children. Props ("$element" :: HTMLElement | I.HTMLaside) props => Children children => Record props -> children -> JSX
aside = typedElement @("$element" :: HTMLElement | I.HTMLaside) htmlNamespace "aside"

audio :: forall props children. Props ("$element" :: HTMLAudioElement | I.HTMLaudio) props => Children children => Record props -> children -> JSX
audio = typedElement @("$element" :: HTMLAudioElement | I.HTMLaudio) htmlNamespace "audio"

b :: forall props children. Props ("$element" :: HTMLElement | I.HTMLb) props => Children children => Record props -> children -> JSX
b = typedElement @("$element" :: HTMLElement | I.HTMLb) htmlNamespace "b"

base :: forall props. Props ("$element" :: HTMLBaseElement | I.HTMLbase) props => Record props -> JSX
base = typedVoidElement @("$element" :: HTMLBaseElement | I.HTMLbase) htmlNamespace "base"

bdi :: forall props children. Props ("$element" :: HTMLElement | I.HTMLbdi) props => Children children => Record props -> children -> JSX
bdi = typedElement @("$element" :: HTMLElement | I.HTMLbdi) htmlNamespace "bdi"

bdo :: forall props children. Props ("$element" :: HTMLElement | I.HTMLbdo) props => Children children => Record props -> children -> JSX
bdo = typedElement @("$element" :: HTMLElement | I.HTMLbdo) htmlNamespace "bdo"

blockquote :: forall props children. Props ("$element" :: HTMLQuoteElement | I.HTMLblockquote) props => Children children => Record props -> children -> JSX
blockquote = typedElement @("$element" :: HTMLQuoteElement | I.HTMLblockquote) htmlNamespace "blockquote"

body :: forall props children. Props ("$element" :: HTMLBodyElement | I.HTMLbody) props => Children children => Record props -> children -> JSX
body = typedElement @("$element" :: HTMLBodyElement | I.HTMLbody) htmlNamespace "body"

br :: forall props. Props ("$element" :: HTMLBRElement | I.HTMLbr) props => Record props -> JSX
br = typedVoidElement @("$element" :: HTMLBRElement | I.HTMLbr) htmlNamespace "br"

button :: forall props children. Props ("$element" :: HTMLButtonElement | I.HTMLbutton) props => Children children => Record props -> children -> JSX
button = typedElement @("$element" :: HTMLButtonElement | I.HTMLbutton) htmlNamespace "button"

canvas :: forall props children. Props ("$element" :: HTMLCanvasElement | I.HTMLcanvas) props => Children children => Record props -> children -> JSX
canvas = typedElement @("$element" :: HTMLCanvasElement | I.HTMLcanvas) htmlNamespace "canvas"

caption :: forall props children. Props ("$element" :: HTMLTableCaptionElement | I.HTMLcaption) props => Children children => Record props -> children -> JSX
caption = typedElement @("$element" :: HTMLTableCaptionElement | I.HTMLcaption) htmlNamespace "caption"

cite :: forall props children. Props ("$element" :: HTMLElement | I.HTMLcite) props => Children children => Record props -> children -> JSX
cite = typedElement @("$element" :: HTMLElement | I.HTMLcite) htmlNamespace "cite"

code :: forall props children. Props ("$element" :: HTMLElement | I.HTMLcode) props => Children children => Record props -> children -> JSX
code = typedElement @("$element" :: HTMLElement | I.HTMLcode) htmlNamespace "code"

col :: forall props. Props ("$element" :: HTMLTableColElement | I.HTMLcol) props => Record props -> JSX
col = typedVoidElement @("$element" :: HTMLTableColElement | I.HTMLcol) htmlNamespace "col"

colgroup :: forall props children. Props ("$element" :: HTMLTableColElement | I.HTMLcolgroup) props => Children children => Record props -> children -> JSX
colgroup = typedElement @("$element" :: HTMLTableColElement | I.HTMLcolgroup) htmlNamespace "colgroup"

command :: forall props. Props ("$element" :: HTMLElement | I.HTMLcommand) props => Record props -> JSX
command = typedVoidElement @("$element" :: HTMLElement | I.HTMLcommand) htmlNamespace "command"

datalist :: forall props children. Props ("$element" :: HTMLDataListElement | I.HTMLdatalist) props => Children children => Record props -> children -> JSX
datalist = typedElement @("$element" :: HTMLDataListElement | I.HTMLdatalist) htmlNamespace "datalist"

dd :: forall props children. Props ("$element" :: HTMLElement | I.HTMLdd) props => Children children => Record props -> children -> JSX
dd = typedElement @("$element" :: HTMLElement | I.HTMLdd) htmlNamespace "dd"

del :: forall props children. Props ("$element" :: HTMLModElement | I.HTMLdel) props => Children children => Record props -> children -> JSX
del = typedElement @("$element" :: HTMLModElement | I.HTMLdel) htmlNamespace "del"

details :: forall props children. Props ("$element" :: HTMLElement | I.HTMLdetails) props => Children children => Record props -> children -> JSX
details = typedElement @("$element" :: HTMLElement | I.HTMLdetails) htmlNamespace "details"

dfn :: forall props children. Props ("$element" :: HTMLElement | I.HTMLdfn) props => Children children => Record props -> children -> JSX
dfn = typedElement @("$element" :: HTMLElement | I.HTMLdfn) htmlNamespace "dfn"

dialog :: forall props children. Props ("$element" :: HTMLDialogElement | I.HTMLdialog) props => Children children => Record props -> children -> JSX
dialog = typedElement @("$element" :: HTMLDialogElement | I.HTMLdialog) htmlNamespace "dialog"

div :: forall props children. Props ("$element" :: HTMLDivElement | I.HTMLdiv) props => Children children => Record props -> children -> JSX
div = typedElement @("$element" :: HTMLDivElement | I.HTMLdiv) htmlNamespace "div"

dl :: forall props children. Props ("$element" :: HTMLDListElement | I.HTMLdl) props => Children children => Record props -> children -> JSX
dl = typedElement @("$element" :: HTMLDListElement | I.HTMLdl) htmlNamespace "dl"

dt :: forall props children. Props ("$element" :: HTMLElement | I.HTMLdt) props => Children children => Record props -> children -> JSX
dt = typedElement @("$element" :: HTMLElement | I.HTMLdt) htmlNamespace "dt"

em :: forall props children. Props ("$element" :: HTMLElement | I.HTMLem) props => Children children => Record props -> children -> JSX
em = typedElement @("$element" :: HTMLElement | I.HTMLem) htmlNamespace "em"

embed :: forall props. Props ("$element" :: HTMLEmbedElement | I.HTMLembed) props => Record props -> JSX
embed = typedVoidElement @("$element" :: HTMLEmbedElement | I.HTMLembed) htmlNamespace "embed"

fieldset :: forall props children. Props ("$element" :: HTMLFieldSetElement | I.HTMLfieldset) props => Children children => Record props -> children -> JSX
fieldset = typedElement @("$element" :: HTMLFieldSetElement | I.HTMLfieldset) htmlNamespace "fieldset"

figcaption :: forall props children. Props ("$element" :: HTMLElement | I.HTMLfigcaption) props => Children children => Record props -> children -> JSX
figcaption = typedElement @("$element" :: HTMLElement | I.HTMLfigcaption) htmlNamespace "figcaption"

figure :: forall props children. Props ("$element" :: HTMLElement | I.HTMLfigure) props => Children children => Record props -> children -> JSX
figure = typedElement @("$element" :: HTMLElement | I.HTMLfigure) htmlNamespace "figure"

footer :: forall props children. Props ("$element" :: HTMLElement | I.HTMLfooter) props => Children children => Record props -> children -> JSX
footer = typedElement @("$element" :: HTMLElement | I.HTMLfooter) htmlNamespace "footer"

form :: forall props children. Props ("$element" :: HTMLFormElement | I.HTMLform) props => Children children => Record props -> children -> JSX
form = typedElement @("$element" :: HTMLFormElement | I.HTMLform) htmlNamespace "form"

h1 :: forall props children. Props ("$element" :: HTMLHeadingElement | I.HTMLh1) props => Children children => Record props -> children -> JSX
h1 = typedElement @("$element" :: HTMLHeadingElement | I.HTMLh1) htmlNamespace "h1"

h2 :: forall props children. Props ("$element" :: HTMLHeadingElement | I.HTMLh2) props => Children children => Record props -> children -> JSX
h2 = typedElement @("$element" :: HTMLHeadingElement | I.HTMLh2) htmlNamespace "h2"

h3 :: forall props children. Props ("$element" :: HTMLHeadingElement | I.HTMLh3) props => Children children => Record props -> children -> JSX
h3 = typedElement @("$element" :: HTMLHeadingElement | I.HTMLh3) htmlNamespace "h3"

h4 :: forall props children. Props ("$element" :: HTMLHeadingElement | I.HTMLh4) props => Children children => Record props -> children -> JSX
h4 = typedElement @("$element" :: HTMLHeadingElement | I.HTMLh4) htmlNamespace "h4"

h5 :: forall props children. Props ("$element" :: HTMLHeadingElement | I.HTMLh5) props => Children children => Record props -> children -> JSX
h5 = typedElement @("$element" :: HTMLHeadingElement | I.HTMLh5) htmlNamespace "h5"

h6 :: forall props children. Props ("$element" :: HTMLHeadingElement | I.HTMLh6) props => Children children => Record props -> children -> JSX
h6 = typedElement @("$element" :: HTMLHeadingElement | I.HTMLh6) htmlNamespace "h6"

head :: forall props children. Props ("$element" :: HTMLHeadElement | I.HTMLhead) props => Children children => Record props -> children -> JSX
head = typedElement @("$element" :: HTMLHeadElement | I.HTMLhead) htmlNamespace "head"

header :: forall props children. Props ("$element" :: HTMLElement | I.HTMLheader) props => Children children => Record props -> children -> JSX
header = typedElement @("$element" :: HTMLElement | I.HTMLheader) htmlNamespace "header"

hr :: forall props. Props ("$element" :: HTMLHRElement | I.HTMLhr) props => Record props -> JSX
hr = typedVoidElement @("$element" :: HTMLHRElement | I.HTMLhr) htmlNamespace "hr"

html :: forall props children. Props ("$element" :: HTMLHtmlElement | I.HTMLhtml) props => Children children => Record props -> children -> JSX
html = typedElement @("$element" :: HTMLHtmlElement | I.HTMLhtml) htmlNamespace "html"

i :: forall props children. Props ("$element" :: HTMLElement | I.HTMLi) props => Children children => Record props -> children -> JSX
i = typedElement @("$element" :: HTMLElement | I.HTMLi) htmlNamespace "i"

iframe :: forall props children. Props ("$element" :: HTMLIFrameElement | I.HTMLiframe) props => Children children => Record props -> children -> JSX
iframe = typedElement @("$element" :: HTMLIFrameElement | I.HTMLiframe) htmlNamespace "iframe"

img :: forall props. Props ("$element" :: HTMLImageElement | I.HTMLimg) props => Record props -> JSX
img = typedVoidElement @("$element" :: HTMLImageElement | I.HTMLimg) htmlNamespace "img"

input :: forall props. Props ("$element" :: HTMLInputElement | I.HTMLinput) props => Record props -> JSX
input = typedVoidElement @("$element" :: HTMLInputElement | I.HTMLinput) htmlNamespace "input"

ins :: forall props children. Props ("$element" :: HTMLModElement | I.HTMLins) props => Children children => Record props -> children -> JSX
ins = typedElement @("$element" :: HTMLModElement | I.HTMLins) htmlNamespace "ins"

kbd :: forall props children. Props ("$element" :: HTMLElement | I.HTMLkbd) props => Children children => Record props -> children -> JSX
kbd = typedElement @("$element" :: HTMLElement | I.HTMLkbd) htmlNamespace "kbd"

label :: forall props children. Props ("$element" :: HTMLLabelElement | I.HTMLlabel) props => Children children => Record props -> children -> JSX
label = typedElement @("$element" :: HTMLLabelElement | I.HTMLlabel) htmlNamespace "label"

legend :: forall props children. Props ("$element" :: HTMLLegendElement | I.HTMLlegend) props => Children children => Record props -> children -> JSX
legend = typedElement @("$element" :: HTMLLegendElement | I.HTMLlegend) htmlNamespace "legend"

li :: forall props children. Props ("$element" :: HTMLLIElement | I.HTMLli) props => Children children => Record props -> children -> JSX
li = typedElement @("$element" :: HTMLLIElement | I.HTMLli) htmlNamespace "li"

link :: forall props. Props ("$element" :: HTMLLinkElement | I.HTMLlink) props => Record props -> JSX
link = typedVoidElement @("$element" :: HTMLLinkElement | I.HTMLlink) htmlNamespace "link"

main :: forall props children. Props ("$element" :: HTMLElement | I.HTMLmain) props => Children children => Record props -> children -> JSX
main = typedElement @("$element" :: HTMLElement | I.HTMLmain) htmlNamespace "main"

map :: forall props children. Props ("$element" :: HTMLMapElement | I.HTMLmap) props => Children children => Record props -> children -> JSX
map = typedElement @("$element" :: HTMLMapElement | I.HTMLmap) htmlNamespace "map"

mark :: forall props children. Props ("$element" :: HTMLElement | I.HTMLmark) props => Children children => Record props -> children -> JSX
mark = typedElement @("$element" :: HTMLElement | I.HTMLmark) htmlNamespace "mark"

menu :: forall props children. Props ("$element" :: HTMLElement | I.HTMLmenu) props => Children children => Record props -> children -> JSX
menu = typedElement @("$element" :: HTMLElement | I.HTMLmenu) htmlNamespace "menu"

menuitem :: forall props children. Props ("$element" :: HTMLElement | I.HTMLmenuitem) props => Children children => Record props -> children -> JSX
menuitem = typedElement @("$element" :: HTMLElement | I.HTMLmenuitem) htmlNamespace "menuitem"

meta :: forall props. Props ("$element" :: HTMLMetaElement | I.HTMLmeta) props => Record props -> JSX
meta = typedVoidElement @("$element" :: HTMLMetaElement | I.HTMLmeta) htmlNamespace "meta"

meter :: forall props children. Props ("$element" :: HTMLMeterElement | I.HTMLmeter) props => Children children => Record props -> children -> JSX
meter = typedElement @("$element" :: HTMLMeterElement | I.HTMLmeter) htmlNamespace "meter"

nav :: forall props children. Props ("$element" :: HTMLElement | I.HTMLnav) props => Children children => Record props -> children -> JSX
nav = typedElement @("$element" :: HTMLElement | I.HTMLnav) htmlNamespace "nav"

noscript :: forall props children. Props ("$element" :: HTMLElement | I.HTMLnoscript) props => Children children => Record props -> children -> JSX
noscript = typedElement @("$element" :: HTMLElement | I.HTMLnoscript) htmlNamespace "noscript"

object :: forall props children. Props ("$element" :: HTMLObjectElement | I.HTMLobject) props => Children children => Record props -> children -> JSX
object = typedElement @("$element" :: HTMLObjectElement | I.HTMLobject) htmlNamespace "object"

ol :: forall props children. Props ("$element" :: HTMLOListElement | I.HTMLol) props => Children children => Record props -> children -> JSX
ol = typedElement @("$element" :: HTMLOListElement | I.HTMLol) htmlNamespace "ol"

optgroup :: forall props children. Props ("$element" :: HTMLOptGroupElement | I.HTMLoptgroup) props => Children children => Record props -> children -> JSX
optgroup = typedElement @("$element" :: HTMLOptGroupElement | I.HTMLoptgroup) htmlNamespace "optgroup"

option :: forall props children. Props ("$element" :: HTMLOptionElement | I.HTMLoption) props => Children children => Record props -> children -> JSX
option = typedElement @("$element" :: HTMLOptionElement | I.HTMLoption) htmlNamespace "option"

output :: forall props children. Props ("$element" :: HTMLOutputElement | I.HTMLoutput) props => Children children => Record props -> children -> JSX
output = typedElement @("$element" :: HTMLOutputElement | I.HTMLoutput) htmlNamespace "output"

p :: forall props children. Props ("$element" :: HTMLParagraphElement | I.HTMLp) props => Children children => Record props -> children -> JSX
p = typedElement @("$element" :: HTMLParagraphElement | I.HTMLp) htmlNamespace "p"

param :: forall props. Props ("$element" :: HTMLParamElement | I.HTMLparam) props => Record props -> JSX
param = typedVoidElement @("$element" :: HTMLParamElement | I.HTMLparam) htmlNamespace "param"

picture :: forall props children. Props ("$element" :: HTMLElement | I.Interactive ()) props => Children children => Record props -> children -> JSX
picture = typedElement @("$element" :: HTMLElement | I.Interactive ()) htmlNamespace "picture"

pre :: forall props children. Props ("$element" :: HTMLPreElement | I.HTMLpre) props => Children children => Record props -> children -> JSX
pre = typedElement @("$element" :: HTMLPreElement | I.HTMLpre) htmlNamespace "pre"

progress :: forall props children. Props ("$element" :: HTMLProgressElement | I.HTMLprogress) props => Children children => Record props -> children -> JSX
progress = typedElement @("$element" :: HTMLProgressElement | I.HTMLprogress) htmlNamespace "progress"

q :: forall props children. Props ("$element" :: HTMLQuoteElement | I.HTMLq) props => Children children => Record props -> children -> JSX
q = typedElement @("$element" :: HTMLQuoteElement | I.HTMLq) htmlNamespace "q"

rp :: forall props children. Props ("$element" :: HTMLElement | I.HTMLrp) props => Children children => Record props -> children -> JSX
rp = typedElement @("$element" :: HTMLElement | I.HTMLrp) htmlNamespace "rp"

rt :: forall props children. Props ("$element" :: HTMLElement | I.HTMLrt) props => Children children => Record props -> children -> JSX
rt = typedElement @("$element" :: HTMLElement | I.HTMLrt) htmlNamespace "rt"

ruby :: forall props children. Props ("$element" :: HTMLElement | I.HTMLruby) props => Children children => Record props -> children -> JSX
ruby = typedElement @("$element" :: HTMLElement | I.HTMLruby) htmlNamespace "ruby"

samp :: forall props children. Props ("$element" :: HTMLElement | I.HTMLsamp) props => Children children => Record props -> children -> JSX
samp = typedElement @("$element" :: HTMLElement | I.HTMLsamp) htmlNamespace "samp"

script :: forall props children. Props ("$element" :: HTMLScriptElement | I.HTMLscript) props => Children children => Record props -> children -> JSX
script = typedElement @("$element" :: HTMLScriptElement | I.HTMLscript) htmlNamespace "script"

search :: forall props children. Props ("$element" :: HTMLElement | I.Interactive ()) props => Children children => Record props -> children -> JSX
search = typedElement @("$element" :: HTMLElement | I.Interactive ()) htmlNamespace "search"

section :: forall props children. Props ("$element" :: HTMLElement | I.HTMLsection) props => Children children => Record props -> children -> JSX
section = typedElement @("$element" :: HTMLElement | I.HTMLsection) htmlNamespace "section"

select :: forall props children. Props ("$element" :: HTMLSelectElement | I.HTMLselect) props => Children children => Record props -> children -> JSX
select = typedElement @("$element" :: HTMLSelectElement | I.HTMLselect) htmlNamespace "select"

slot :: forall props children. Props ("$element" :: HTMLElement | I.Interactive ()) props => Children children => Record props -> children -> JSX
slot = typedElement @("$element" :: HTMLElement | I.Interactive ()) htmlNamespace "slot"

small :: forall props children. Props ("$element" :: HTMLElement | I.HTMLsmall) props => Children children => Record props -> children -> JSX
small = typedElement @("$element" :: HTMLElement | I.HTMLsmall) htmlNamespace "small"

source :: forall props. Props ("$element" :: HTMLSourceElement | I.HTMLsource) props => Record props -> JSX
source = typedVoidElement @("$element" :: HTMLSourceElement | I.HTMLsource) htmlNamespace "source"

span :: forall props children. Props ("$element" :: HTMLSpanElement | I.HTMLspan) props => Children children => Record props -> children -> JSX
span = typedElement @("$element" :: HTMLSpanElement | I.HTMLspan) htmlNamespace "span"

strong :: forall props children. Props ("$element" :: HTMLElement | I.HTMLstrong) props => Children children => Record props -> children -> JSX
strong = typedElement @("$element" :: HTMLElement | I.HTMLstrong) htmlNamespace "strong"

style :: forall props children. Props ("$element" :: HTMLStyleElement | I.HTMLstyle) props => Children children => Record props -> children -> JSX
style = typedElement @("$element" :: HTMLStyleElement | I.HTMLstyle) htmlNamespace "style"

sub :: forall props children. Props ("$element" :: HTMLElement | I.HTMLsub) props => Children children => Record props -> children -> JSX
sub = typedElement @("$element" :: HTMLElement | I.HTMLsub) htmlNamespace "sub"

summary :: forall props children. Props ("$element" :: HTMLElement | I.HTMLsummary) props => Children children => Record props -> children -> JSX
summary = typedElement @("$element" :: HTMLElement | I.HTMLsummary) htmlNamespace "summary"

sup :: forall props children. Props ("$element" :: HTMLElement | I.HTMLsup) props => Children children => Record props -> children -> JSX
sup = typedElement @("$element" :: HTMLElement | I.HTMLsup) htmlNamespace "sup"

table :: forall props children. Props ("$element" :: HTMLTableElement | I.HTMLtable) props => Children children => Record props -> children -> JSX
table = typedElement @("$element" :: HTMLTableElement | I.HTMLtable) htmlNamespace "table"

tbody :: forall props children. Props ("$element" :: HTMLTableSectionElement | I.HTMLtbody) props => Children children => Record props -> children -> JSX
tbody = typedElement @("$element" :: HTMLTableSectionElement | I.HTMLtbody) htmlNamespace "tbody"

td :: forall props children. Props ("$element" :: HTMLTableDataCellElement | I.HTMLtd) props => Children children => Record props -> children -> JSX
td = typedElement @("$element" :: HTMLTableDataCellElement | I.HTMLtd) htmlNamespace "td"

template :: forall props children. Props ("$element" :: HTMLTemplateElement | I.Interactive ()) props => Children children => Record props -> children -> JSX
template = typedElement @("$element" :: HTMLTemplateElement | I.Interactive ()) htmlNamespace "template"

textarea :: forall props children. Props ("$element" :: HTMLTextAreaElement | I.HTMLtextarea) props => Children children => Record props -> children -> JSX
textarea = typedElement @("$element" :: HTMLTextAreaElement | I.HTMLtextarea) htmlNamespace "textarea"

tfoot :: forall props children. Props ("$element" :: HTMLTableSectionElement | I.HTMLtfoot) props => Children children => Record props -> children -> JSX
tfoot = typedElement @("$element" :: HTMLTableSectionElement | I.HTMLtfoot) htmlNamespace "tfoot"

th :: forall props children. Props ("$element" :: HTMLTableHeaderCellElement | I.HTMLth) props => Children children => Record props -> children -> JSX
th = typedElement @("$element" :: HTMLTableHeaderCellElement | I.HTMLth) htmlNamespace "th"

thead :: forall props children. Props ("$element" :: HTMLTableSectionElement | I.HTMLthead) props => Children children => Record props -> children -> JSX
thead = typedElement @("$element" :: HTMLTableSectionElement | I.HTMLthead) htmlNamespace "thead"

time :: forall props children. Props ("$element" :: HTMLTimeElement | I.HTMLtime) props => Children children => Record props -> children -> JSX
time = typedElement @("$element" :: HTMLTimeElement | I.HTMLtime) htmlNamespace "time"

title :: forall props children. Props ("$element" :: HTMLTitleElement | I.HTMLtitle) props => Children children => Record props -> children -> JSX
title = typedElement @("$element" :: HTMLTitleElement | I.HTMLtitle) htmlNamespace "title"

tr :: forall props children. Props ("$element" :: HTMLTableRowElement | I.HTMLtr) props => Children children => Record props -> children -> JSX
tr = typedElement @("$element" :: HTMLTableRowElement | I.HTMLtr) htmlNamespace "tr"

track :: forall props. Props ("$element" :: HTMLTrackElement | I.HTMLtrack) props => Record props -> JSX
track = typedVoidElement @("$element" :: HTMLTrackElement | I.HTMLtrack) htmlNamespace "track"

u :: forall props children. Props ("$element" :: HTMLElement | I.HTMLu) props => Children children => Record props -> children -> JSX
u = typedElement @("$element" :: HTMLElement | I.HTMLu) htmlNamespace "u"

ul :: forall props children. Props ("$element" :: HTMLUListElement | I.HTMLul) props => Children children => Record props -> children -> JSX
ul = typedElement @("$element" :: HTMLUListElement | I.HTMLul) htmlNamespace "ul"

var :: forall props children. Props ("$element" :: HTMLElement | I.HTMLvar) props => Children children => Record props -> children -> JSX
var = typedElement @("$element" :: HTMLElement | I.HTMLvar) htmlNamespace "var"

video :: forall props children. Props ("$element" :: HTMLVideoElement | I.HTMLvideo) props => Children children => Record props -> children -> JSX
video = typedElement @("$element" :: HTMLVideoElement | I.HTMLvideo) htmlNamespace "video"

wbr :: forall props. Props ("$element" :: HTMLElement | I.HTMLwbr) props => Record props -> JSX
wbr = typedVoidElement @("$element" :: HTMLElement | I.HTMLwbr) htmlNamespace "wbr"
