-- | Element properties, each usable only on elements that support it. Generated by `scripts/gen-dom.mjs`.
module Solid.DOM.Props where

import Prelude

import Web.Clipboard.ClipboardEvent (ClipboardEvent)
import Web.HTML.Event.DragEvent (DragEvent)
import Web.Event.Event (Event)
import Web.UIEvent.FocusEvent (FocusEvent)
import Web.UIEvent.KeyboardEvent (KeyboardEvent)
import Web.UIEvent.MouseEvent (MouseEvent)
import Web.PointerEvent (PointerEvent)
import Web.TouchEvent (TouchEvent)
import Web.UIEvent.WheelEvent (WheelEvent)
import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, bindingProp, eventProp)
import Effect (Effect)

abbr :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (abbr :: a | r)
abbr = bindingProp "abbr" toAttrValue

accept :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (accept :: a | r)
accept = bindingProp "accept" toAttrValue

acceptCharset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (acceptCharset :: a | r)
acceptCharset = bindingProp "accept-charset" toAttrValue

accessKey :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (accessKey :: a | r)
accessKey = bindingProp "accesskey" toAttrValue

action :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (action :: a | r)
action = bindingProp "action" toAttrValue

alt :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (alt :: a | r)
alt = bindingProp "alt" toAttrValue

async :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (async :: a | r)
async = bindingProp "async" toAttrValue

autocomplete :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autocomplete :: a | r)
autocomplete = bindingProp "autocomplete" toAttrValue

autofocus :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autofocus :: a | r)
autofocus = bindingProp "autofocus" toAttrValue

autoplay :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autoplay :: a | r)
autoplay = bindingProp "autoplay" toAttrValue

charset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (charset :: a | r)
charset = bindingProp "charset" toAttrValue

checked :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (checked :: a | r)
checked = bindingProp "checked" toAttrValue

cite :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cite :: a | r)
cite = bindingProp "cite" toAttrValue

class_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (class :: a | r)
class_ = bindingProp "class" toAttrValue

colSpan :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (colSpan :: a | r)
colSpan = bindingProp "colspan" toAttrValue

cols :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cols :: a | r)
cols = bindingProp "cols" toAttrValue

command :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (command :: a | r)
command = bindingProp "command" toAttrValue

content :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (content :: a | r)
content = bindingProp "content" toAttrValue

contentEditable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (contentEditable :: a | r)
contentEditable = bindingProp "contenteditable" toAttrValue

controls :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (controls :: a | r)
controls = bindingProp "controls" toAttrValue

coords :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (coords :: a | r)
coords = bindingProp "coords" toAttrValue

crossOrigin :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (crossOrigin :: a | r)
crossOrigin = bindingProp "crossorigin" toAttrValue

data_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (data :: a | r)
data_ = bindingProp "data" toAttrValue

datetime :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (datetime :: a | r)
datetime = bindingProp "datetime" toAttrValue

default :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (default :: a | r)
default = bindingProp "default" toAttrValue

defer :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (defer :: a | r)
defer = bindingProp "defer" toAttrValue

dir :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dir :: a | r)
dir = bindingProp "dir" toAttrValue

disabled :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (disabled :: a | r)
disabled = bindingProp "disabled" toAttrValue

download :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (download :: a | r)
download = bindingProp "download" toAttrValue

draggable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (draggable :: a | r)
draggable = bindingProp "draggable" toAttrValue

enctype :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (enctype :: a | r)
enctype = bindingProp "enctype" toAttrValue

for :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (for :: a | r)
for = bindingProp "for" toAttrValue

form :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (form :: a | r)
form = bindingProp "form" toAttrValue

formAction :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formAction :: a | r)
formAction = bindingProp "formaction" toAttrValue

formEncType :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formEncType :: a | r)
formEncType = bindingProp "formenctype" toAttrValue

formMethod :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formMethod :: a | r)
formMethod = bindingProp "formmethod" toAttrValue

formNoValidate :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formNoValidate :: a | r)
formNoValidate = bindingProp "formnovalidate" toAttrValue

formTarget :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formTarget :: a | r)
formTarget = bindingProp "formtarget" toAttrValue

headers :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (headers :: a | r)
headers = bindingProp "headers" toAttrValue

height :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (height :: a | r)
height = bindingProp "height" toAttrValue

hidden :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hidden :: a | r)
hidden = bindingProp "hidden" toAttrValue

high :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (high :: a | r)
high = bindingProp "high" toAttrValue

href :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (href :: a | r)
href = bindingProp "href" toAttrValue

hrefLang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hrefLang :: a | r)
hrefLang = bindingProp "hreflang" toAttrValue

hreflang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hreflang :: a | r)
hreflang = bindingProp "hreflang" toAttrValue

httpEquiv :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (httpEquiv :: a | r)
httpEquiv = bindingProp "http-equiv" toAttrValue

icon :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (icon :: a | r)
icon = bindingProp "icon" toAttrValue

id :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (id :: a | r)
id = bindingProp "id" toAttrValue

isMap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (isMap :: a | r)
isMap = bindingProp "ismap" toAttrValue

kind :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (kind :: a | r)
kind = bindingProp "kind" toAttrValue

label :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (label :: a | r)
label = bindingProp "label" toAttrValue

lang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (lang :: a | r)
lang = bindingProp "lang" toAttrValue

list :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (list :: a | r)
list = bindingProp "list" toAttrValue

longDesc :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (longDesc :: a | r)
longDesc = bindingProp "longdesc" toAttrValue

loop :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (loop :: a | r)
loop = bindingProp "loop" toAttrValue

low :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (low :: a | r)
low = bindingProp "low" toAttrValue

manifest :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (manifest :: a | r)
manifest = bindingProp "manifest" toAttrValue

max :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (max :: a | r)
max = bindingProp "max" toAttrValue

maxLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (maxLength :: a | r)
maxLength = bindingProp "maxlength" toAttrValue

media :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (media :: a | r)
media = bindingProp "media" toAttrValue

method :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (method :: a | r)
method = bindingProp "method" toAttrValue

min :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (min :: a | r)
min = bindingProp "min" toAttrValue

minLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (minLength :: a | r)
minLength = bindingProp "minlength" toAttrValue

multiple :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (multiple :: a | r)
multiple = bindingProp "multiple" toAttrValue

muted :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (muted :: a | r)
muted = bindingProp "muted" toAttrValue

name :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (name :: a | r)
name = bindingProp "name" toAttrValue

noValidate :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (noValidate :: a | r)
noValidate = bindingProp "novalidate" toAttrValue

onAbort :: forall r. (Event -> Effect Unit) -> Prop (onAbort :: Event | r)
onAbort = eventProp "onAbort"

onAuxClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onAuxClick :: MouseEvent | r)
onAuxClick = eventProp "onAuxClick"

onBeforeInput :: forall r. (Event -> Effect Unit) -> Prop (onBeforeInput :: Event | r)
onBeforeInput = eventProp "onBeforeInput"

onBeforeUnload :: forall r. (Event -> Effect Unit) -> Prop (onBeforeUnload :: Event | r)
onBeforeUnload = eventProp "onBeforeUnload"

onBlur :: forall r. (FocusEvent -> Effect Unit) -> Prop (onBlur :: FocusEvent | r)
onBlur = eventProp "onBlur"

onCanPlay :: forall r. (Event -> Effect Unit) -> Prop (onCanPlay :: Event | r)
onCanPlay = eventProp "onCanPlay"

onCanPlayThrough :: forall r. (Event -> Effect Unit) -> Prop (onCanPlayThrough :: Event | r)
onCanPlayThrough = eventProp "onCanPlayThrough"

onChange :: forall r. (Event -> Effect Unit) -> Prop (onChange :: Event | r)
onChange = eventProp "onChange"

onClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onClick :: MouseEvent | r)
onClick = eventProp "onClick"

onContextMenu :: forall r. (Event -> Effect Unit) -> Prop (onContextMenu :: Event | r)
onContextMenu = eventProp "onContextMenu"

onCopy :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onCopy :: ClipboardEvent | r)
onCopy = eventProp "onCopy"

onCut :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onCut :: ClipboardEvent | r)
onCut = eventProp "onCut"

onDoubleClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onDoubleClick :: MouseEvent | r)
onDoubleClick = eventProp "onDblClick"

onDrag :: forall r. (DragEvent -> Effect Unit) -> Prop (onDrag :: DragEvent | r)
onDrag = eventProp "onDrag"

onDragEnd :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragEnd :: DragEvent | r)
onDragEnd = eventProp "onDragEnd"

onDragEnter :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragEnter :: DragEvent | r)
onDragEnter = eventProp "onDragEnter"

onDragExit :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragExit :: DragEvent | r)
onDragExit = eventProp "onDragExit"

onDragLeave :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragLeave :: DragEvent | r)
onDragLeave = eventProp "onDragLeave"

onDragOver :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragOver :: DragEvent | r)
onDragOver = eventProp "onDragOver"

onDragStart :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragStart :: DragEvent | r)
onDragStart = eventProp "onDragStart"

onDrop :: forall r. (DragEvent -> Effect Unit) -> Prop (onDrop :: DragEvent | r)
onDrop = eventProp "onDrop"

onDurationChange :: forall r. (Event -> Effect Unit) -> Prop (onDurationChange :: Event | r)
onDurationChange = eventProp "onDurationChange"

onEmptied :: forall r. (Event -> Effect Unit) -> Prop (onEmptied :: Event | r)
onEmptied = eventProp "onEmptied"

onEnded :: forall r. (Event -> Effect Unit) -> Prop (onEnded :: Event | r)
onEnded = eventProp "onEnded"

onError :: forall r. (Event -> Effect Unit) -> Prop (onError :: Event | r)
onError = eventProp "onError"

onFocus :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocus :: FocusEvent | r)
onFocus = eventProp "onFocus"

onFocusIn :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocusIn :: FocusEvent | r)
onFocusIn = eventProp "onFocusIn"

onFocusOut :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocusOut :: FocusEvent | r)
onFocusOut = eventProp "onFocusOut"

onGotPointerCapture :: forall r. (PointerEvent -> Effect Unit) -> Prop (onGotPointerCapture :: PointerEvent | r)
onGotPointerCapture = eventProp "onGotPointerCapture"

onHashChange :: forall r. (Event -> Effect Unit) -> Prop (onHashChange :: Event | r)
onHashChange = eventProp "onHashChange"

onInput :: forall r. (Event -> Effect Unit) -> Prop (onInput :: Event | r)
onInput = eventProp "onInput"

onInvalid :: forall r. (Event -> Effect Unit) -> Prop (onInvalid :: Event | r)
onInvalid = eventProp "onInvalid"

onKeyDown :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyDown :: KeyboardEvent | r)
onKeyDown = eventProp "onKeyDown"

onKeyPress :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyPress :: KeyboardEvent | r)
onKeyPress = eventProp "onKeyPress"

onKeyUp :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyUp :: KeyboardEvent | r)
onKeyUp = eventProp "onKeyUp"

onLoad :: forall r. (Event -> Effect Unit) -> Prop (onLoad :: Event | r)
onLoad = eventProp "onLoad"

onLoadStart :: forall r. (Event -> Effect Unit) -> Prop (onLoadStart :: Event | r)
onLoadStart = eventProp "onLoadStart"

onLoadedData :: forall r. (Event -> Effect Unit) -> Prop (onLoadedData :: Event | r)
onLoadedData = eventProp "onLoadedData"

onLoadedMetadata :: forall r. (Event -> Effect Unit) -> Prop (onLoadedMetadata :: Event | r)
onLoadedMetadata = eventProp "onLoadedMetadata"

onLostPointerCapture :: forall r. (PointerEvent -> Effect Unit) -> Prop (onLostPointerCapture :: PointerEvent | r)
onLostPointerCapture = eventProp "onLostPointerCapture"

onMouseDown :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseDown :: MouseEvent | r)
onMouseDown = eventProp "onMouseDown"

onMouseEnter :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseEnter :: MouseEvent | r)
onMouseEnter = eventProp "onMouseEnter"

onMouseLeave :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseLeave :: MouseEvent | r)
onMouseLeave = eventProp "onMouseLeave"

onMouseMove :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseMove :: MouseEvent | r)
onMouseMove = eventProp "onMouseMove"

onMouseOut :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseOut :: MouseEvent | r)
onMouseOut = eventProp "onMouseOut"

onMouseOver :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseOver :: MouseEvent | r)
onMouseOver = eventProp "onMouseOver"

onMouseUp :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseUp :: MouseEvent | r)
onMouseUp = eventProp "onMouseUp"

onPageHide :: forall r. (Event -> Effect Unit) -> Prop (onPageHide :: Event | r)
onPageHide = eventProp "onPageHide"

onPageShow :: forall r. (Event -> Effect Unit) -> Prop (onPageShow :: Event | r)
onPageShow = eventProp "onPageShow"

onPaste :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onPaste :: ClipboardEvent | r)
onPaste = eventProp "onPaste"

onPause :: forall r. (Event -> Effect Unit) -> Prop (onPause :: Event | r)
onPause = eventProp "onPause"

onPlay :: forall r. (Event -> Effect Unit) -> Prop (onPlay :: Event | r)
onPlay = eventProp "onPlay"

onPlaying :: forall r. (Event -> Effect Unit) -> Prop (onPlaying :: Event | r)
onPlaying = eventProp "onPlaying"

onPointerCancel :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerCancel :: PointerEvent | r)
onPointerCancel = eventProp "onPointerCancel"

onPointerDown :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerDown :: PointerEvent | r)
onPointerDown = eventProp "onPointerDown"

onPointerEnter :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerEnter :: PointerEvent | r)
onPointerEnter = eventProp "onPointerEnter"

onPointerLeave :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerLeave :: PointerEvent | r)
onPointerLeave = eventProp "onPointerLeave"

onPointerMove :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerMove :: PointerEvent | r)
onPointerMove = eventProp "onPointerMove"

onPointerOut :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerOut :: PointerEvent | r)
onPointerOut = eventProp "onPointerOut"

onPointerOver :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerOver :: PointerEvent | r)
onPointerOver = eventProp "onPointerOver"

onPointerUp :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerUp :: PointerEvent | r)
onPointerUp = eventProp "onPointerUp"

onProgress :: forall r. (Event -> Effect Unit) -> Prop (onProgress :: Event | r)
onProgress = eventProp "onProgress"

onRateChange :: forall r. (Event -> Effect Unit) -> Prop (onRateChange :: Event | r)
onRateChange = eventProp "onRateChange"

onReset :: forall r. (Event -> Effect Unit) -> Prop (onReset :: Event | r)
onReset = eventProp "onReset"

onResize :: forall r. (Event -> Effect Unit) -> Prop (onResize :: Event | r)
onResize = eventProp "onResize"

onScroll :: forall r. (Event -> Effect Unit) -> Prop (onScroll :: Event | r)
onScroll = eventProp "onScroll"

onSearch :: forall r. (Event -> Effect Unit) -> Prop (onSearch :: Event | r)
onSearch = eventProp "onSearch"

onSeeked :: forall r. (Event -> Effect Unit) -> Prop (onSeeked :: Event | r)
onSeeked = eventProp "onSeeked"

onSeeking :: forall r. (Event -> Effect Unit) -> Prop (onSeeking :: Event | r)
onSeeking = eventProp "onSeeking"

onSelect :: forall r. (Event -> Effect Unit) -> Prop (onSelect :: Event | r)
onSelect = eventProp "onSelect"

onStalled :: forall r. (Event -> Effect Unit) -> Prop (onStalled :: Event | r)
onStalled = eventProp "onStalled"

onSubmit :: forall r. (Event -> Effect Unit) -> Prop (onSubmit :: Event | r)
onSubmit = eventProp "onSubmit"

onSuspend :: forall r. (Event -> Effect Unit) -> Prop (onSuspend :: Event | r)
onSuspend = eventProp "onSuspend"

onTimeUpdate :: forall r. (Event -> Effect Unit) -> Prop (onTimeUpdate :: Event | r)
onTimeUpdate = eventProp "onTimeUpdate"

onTouchCancel :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchCancel :: TouchEvent | r)
onTouchCancel = eventProp "onTouchCancel"

onTouchEnd :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchEnd :: TouchEvent | r)
onTouchEnd = eventProp "onTouchEnd"

onTouchEnter :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchEnter :: TouchEvent | r)
onTouchEnter = eventProp "onTouchEnter"

onTouchLeave :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchLeave :: TouchEvent | r)
onTouchLeave = eventProp "onTouchLeave"

onTouchMove :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchMove :: TouchEvent | r)
onTouchMove = eventProp "onTouchMove"

onTouchStart :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchStart :: TouchEvent | r)
onTouchStart = eventProp "onTouchStart"

onTransitionEnd :: forall r. (Event -> Effect Unit) -> Prop (onTransitionEnd :: Event | r)
onTransitionEnd = eventProp "onTransitionEnd"

onUnload :: forall r. (Event -> Effect Unit) -> Prop (onUnload :: Event | r)
onUnload = eventProp "onUnload"

onVolumeChange :: forall r. (Event -> Effect Unit) -> Prop (onVolumeChange :: Event | r)
onVolumeChange = eventProp "onVolumeChange"

onWaiting :: forall r. (Event -> Effect Unit) -> Prop (onWaiting :: Event | r)
onWaiting = eventProp "onWaiting"

onWheel :: forall r. (WheelEvent -> Effect Unit) -> Prop (onWheel :: WheelEvent | r)
onWheel = eventProp "onWheel"

open :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (open :: a | r)
open = bindingProp "open" toAttrValue

optimum :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (optimum :: a | r)
optimum = bindingProp "optimum" toAttrValue

pattern :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pattern :: a | r)
pattern = bindingProp "pattern" toAttrValue

placeholder :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (placeholder :: a | r)
placeholder = bindingProp "placeholder" toAttrValue

poster :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (poster :: a | r)
poster = bindingProp "poster" toAttrValue

preload :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (preload :: a | r)
preload = bindingProp "preload" toAttrValue

radioGroup :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (radioGroup :: a | r)
radioGroup = bindingProp "radiogroup" toAttrValue

readOnly :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (readOnly :: a | r)
readOnly = bindingProp "readonly" toAttrValue

rel :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rel :: a | r)
rel = bindingProp "rel" toAttrValue

required :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (required :: a | r)
required = bindingProp "required" toAttrValue

reversed :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (reversed :: a | r)
reversed = bindingProp "reversed" toAttrValue

rowSpan :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rowSpan :: a | r)
rowSpan = bindingProp "rowspan" toAttrValue

rows :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rows :: a | r)
rows = bindingProp "rows" toAttrValue

sandbox :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sandbox :: a | r)
sandbox = bindingProp "sandbox" toAttrValue

scope :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (scope :: a | r)
scope = bindingProp "scope" toAttrValue

scoped :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (scoped :: a | r)
scoped = bindingProp "scoped" toAttrValue

selected :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (selected :: a | r)
selected = bindingProp "selected" toAttrValue

selectedIndex :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (selectedIndex :: a | r)
selectedIndex = bindingProp "selectedindex" toAttrValue

shape :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (shape :: a | r)
shape = bindingProp "shape" toAttrValue

size :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (size :: a | r)
size = bindingProp "size" toAttrValue

sizes :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sizes :: a | r)
sizes = bindingProp "sizes" toAttrValue

sortable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sortable :: a | r)
sortable = bindingProp "sortable" toAttrValue

sorted :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sorted :: a | r)
sorted = bindingProp "sorted" toAttrValue

span :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (span :: a | r)
span = bindingProp "span" toAttrValue

spellcheck :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (spellcheck :: a | r)
spellcheck = bindingProp "spellcheck" toAttrValue

src :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (src :: a | r)
src = bindingProp "src" toAttrValue

srcDoc :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (srcDoc :: a | r)
srcDoc = bindingProp "srcdoc" toAttrValue

srcLang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (srcLang :: a | r)
srcLang = bindingProp "srclang" toAttrValue

start :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (start :: a | r)
start = bindingProp "start" toAttrValue

step :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (step :: a | r)
step = bindingProp "step" toAttrValue

style :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (style :: a | r)
style = bindingProp "style" toAttrValue

tabIndex :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (tabIndex :: a | r)
tabIndex = bindingProp "tabindex" toAttrValue

target :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (target :: a | r)
target = bindingProp "target" toAttrValue

title :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (title :: a | r)
title = bindingProp "title" toAttrValue

type_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (type :: a | r)
type_ = bindingProp "type" toAttrValue

useMap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (useMap :: a | r)
useMap = bindingProp "usemap" toAttrValue

value :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (value :: a | r)
value = bindingProp "value" toAttrValue

width :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (width :: a | r)
width = bindingProp "width" toAttrValue

wrap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (wrap :: a | r)
wrap = bindingProp "wrap" toAttrValue

xmlns :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (xmlns :: a | r)
xmlns = bindingProp "xmlns" toAttrValue
