-- | Element properties, each usable only on elements that support it. Generated by `scripts/gen-dom.mjs`.
module Solid.DOM.Props where

import Prelude

import Web.Clipboard.ClipboardEvent (ClipboardEvent)
import Web.HTML.Event.DragEvent (DragEvent)
import Web.Event.Event (Event)
import Web.UIEvent.FocusEvent (FocusEvent)
import Web.UIEvent.KeyboardEvent (KeyboardEvent)
import Web.UIEvent.MouseEvent (MouseEvent)
import Web.PointerEvent (PointerEvent)
import Web.TouchEvent (TouchEvent)
import Web.UIEvent.WheelEvent (WheelEvent)
import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, binding, bindingProp, eventProp)
import Effect (Effect)

abbr :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (abbr :: a | r)
abbr v = bindingProp "abbr" toAttrValue (binding v)

accept :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (accept :: a | r)
accept v = bindingProp "accept" toAttrValue (binding v)

acceptCharset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (acceptCharset :: a | r)
acceptCharset v = bindingProp "accept-charset" toAttrValue (binding v)

accessKey :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (accessKey :: a | r)
accessKey v = bindingProp "accesskey" toAttrValue (binding v)

action :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (action :: a | r)
action v = bindingProp "action" toAttrValue (binding v)

alt :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (alt :: a | r)
alt v = bindingProp "alt" toAttrValue (binding v)

async :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (async :: a | r)
async v = bindingProp "async" toAttrValue (binding v)

autocomplete :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autocomplete :: a | r)
autocomplete v = bindingProp "autocomplete" toAttrValue (binding v)

autofocus :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autofocus :: a | r)
autofocus v = bindingProp "autofocus" toAttrValue (binding v)

autoplay :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autoplay :: a | r)
autoplay v = bindingProp "autoplay" toAttrValue (binding v)

charset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (charset :: a | r)
charset v = bindingProp "charset" toAttrValue (binding v)

checked :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (checked :: a | r)
checked v = bindingProp "checked" toAttrValue (binding v)

cite :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cite :: a | r)
cite v = bindingProp "cite" toAttrValue (binding v)

class_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (class :: a | r)
class_ v = bindingProp "class" toAttrValue (binding v)

colSpan :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (colSpan :: a | r)
colSpan v = bindingProp "colspan" toAttrValue (binding v)

cols :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cols :: a | r)
cols v = bindingProp "cols" toAttrValue (binding v)

command :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (command :: a | r)
command v = bindingProp "command" toAttrValue (binding v)

content :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (content :: a | r)
content v = bindingProp "content" toAttrValue (binding v)

contentEditable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (contentEditable :: a | r)
contentEditable v = bindingProp "contenteditable" toAttrValue (binding v)

controls :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (controls :: a | r)
controls v = bindingProp "controls" toAttrValue (binding v)

coords :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (coords :: a | r)
coords v = bindingProp "coords" toAttrValue (binding v)

crossOrigin :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (crossOrigin :: a | r)
crossOrigin v = bindingProp "crossorigin" toAttrValue (binding v)

data_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (data :: a | r)
data_ v = bindingProp "data" toAttrValue (binding v)

datetime :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (datetime :: a | r)
datetime v = bindingProp "datetime" toAttrValue (binding v)

default :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (default :: a | r)
default v = bindingProp "default" toAttrValue (binding v)

defer :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (defer :: a | r)
defer v = bindingProp "defer" toAttrValue (binding v)

dir :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dir :: a | r)
dir v = bindingProp "dir" toAttrValue (binding v)

disabled :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (disabled :: a | r)
disabled v = bindingProp "disabled" toAttrValue (binding v)

download :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (download :: a | r)
download v = bindingProp "download" toAttrValue (binding v)

draggable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (draggable :: a | r)
draggable v = bindingProp "draggable" toAttrValue (binding v)

enctype :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (enctype :: a | r)
enctype v = bindingProp "enctype" toAttrValue (binding v)

for :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (for :: a | r)
for v = bindingProp "for" toAttrValue (binding v)

form :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (form :: a | r)
form v = bindingProp "form" toAttrValue (binding v)

formAction :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formAction :: a | r)
formAction v = bindingProp "formaction" toAttrValue (binding v)

formEncType :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formEncType :: a | r)
formEncType v = bindingProp "formenctype" toAttrValue (binding v)

formMethod :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formMethod :: a | r)
formMethod v = bindingProp "formmethod" toAttrValue (binding v)

formNoValidate :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formNoValidate :: a | r)
formNoValidate v = bindingProp "formnovalidate" toAttrValue (binding v)

formTarget :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formTarget :: a | r)
formTarget v = bindingProp "formtarget" toAttrValue (binding v)

headers :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (headers :: a | r)
headers v = bindingProp "headers" toAttrValue (binding v)

height :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (height :: a | r)
height v = bindingProp "height" toAttrValue (binding v)

hidden :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hidden :: a | r)
hidden v = bindingProp "hidden" toAttrValue (binding v)

high :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (high :: a | r)
high v = bindingProp "high" toAttrValue (binding v)

href :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (href :: a | r)
href v = bindingProp "href" toAttrValue (binding v)

hrefLang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hrefLang :: a | r)
hrefLang v = bindingProp "hreflang" toAttrValue (binding v)

hreflang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hreflang :: a | r)
hreflang v = bindingProp "hreflang" toAttrValue (binding v)

httpEquiv :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (httpEquiv :: a | r)
httpEquiv v = bindingProp "http-equiv" toAttrValue (binding v)

icon :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (icon :: a | r)
icon v = bindingProp "icon" toAttrValue (binding v)

id :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (id :: a | r)
id v = bindingProp "id" toAttrValue (binding v)

isMap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (isMap :: a | r)
isMap v = bindingProp "ismap" toAttrValue (binding v)

kind :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (kind :: a | r)
kind v = bindingProp "kind" toAttrValue (binding v)

label :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (label :: a | r)
label v = bindingProp "label" toAttrValue (binding v)

lang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (lang :: a | r)
lang v = bindingProp "lang" toAttrValue (binding v)

list :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (list :: a | r)
list v = bindingProp "list" toAttrValue (binding v)

longDesc :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (longDesc :: a | r)
longDesc v = bindingProp "longdesc" toAttrValue (binding v)

loop :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (loop :: a | r)
loop v = bindingProp "loop" toAttrValue (binding v)

low :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (low :: a | r)
low v = bindingProp "low" toAttrValue (binding v)

manifest :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (manifest :: a | r)
manifest v = bindingProp "manifest" toAttrValue (binding v)

max :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (max :: a | r)
max v = bindingProp "max" toAttrValue (binding v)

maxLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (maxLength :: a | r)
maxLength v = bindingProp "maxlength" toAttrValue (binding v)

media :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (media :: a | r)
media v = bindingProp "media" toAttrValue (binding v)

method :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (method :: a | r)
method v = bindingProp "method" toAttrValue (binding v)

min :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (min :: a | r)
min v = bindingProp "min" toAttrValue (binding v)

minLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (minLength :: a | r)
minLength v = bindingProp "minlength" toAttrValue (binding v)

multiple :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (multiple :: a | r)
multiple v = bindingProp "multiple" toAttrValue (binding v)

muted :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (muted :: a | r)
muted v = bindingProp "muted" toAttrValue (binding v)

name :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (name :: a | r)
name v = bindingProp "name" toAttrValue (binding v)

noValidate :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (noValidate :: a | r)
noValidate v = bindingProp "novalidate" toAttrValue (binding v)

onAbort :: forall r. (Event -> Effect Unit) -> Prop (onAbort :: Event | r)
onAbort = eventProp "onAbort"

onAuxClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onAuxClick :: MouseEvent | r)
onAuxClick = eventProp "onAuxClick"

onBeforeInput :: forall r. (Event -> Effect Unit) -> Prop (onBeforeInput :: Event | r)
onBeforeInput = eventProp "onBeforeInput"

onBeforeUnload :: forall r. (Event -> Effect Unit) -> Prop (onBeforeUnload :: Event | r)
onBeforeUnload = eventProp "onBeforeUnload"

onBlur :: forall r. (FocusEvent -> Effect Unit) -> Prop (onBlur :: FocusEvent | r)
onBlur = eventProp "onBlur"

onCanPlay :: forall r. (Event -> Effect Unit) -> Prop (onCanPlay :: Event | r)
onCanPlay = eventProp "onCanPlay"

onCanPlayThrough :: forall r. (Event -> Effect Unit) -> Prop (onCanPlayThrough :: Event | r)
onCanPlayThrough = eventProp "onCanPlayThrough"

onChange :: forall r. (Event -> Effect Unit) -> Prop (onChange :: Event | r)
onChange = eventProp "onChange"

onClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onClick :: MouseEvent | r)
onClick = eventProp "onClick"

onContextMenu :: forall r. (Event -> Effect Unit) -> Prop (onContextMenu :: Event | r)
onContextMenu = eventProp "onContextMenu"

onCopy :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onCopy :: ClipboardEvent | r)
onCopy = eventProp "onCopy"

onCut :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onCut :: ClipboardEvent | r)
onCut = eventProp "onCut"

onDoubleClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onDoubleClick :: MouseEvent | r)
onDoubleClick = eventProp "onDblClick"

onDrag :: forall r. (DragEvent -> Effect Unit) -> Prop (onDrag :: DragEvent | r)
onDrag = eventProp "onDrag"

onDragEnd :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragEnd :: DragEvent | r)
onDragEnd = eventProp "onDragEnd"

onDragEnter :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragEnter :: DragEvent | r)
onDragEnter = eventProp "onDragEnter"

onDragExit :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragExit :: DragEvent | r)
onDragExit = eventProp "onDragExit"

onDragLeave :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragLeave :: DragEvent | r)
onDragLeave = eventProp "onDragLeave"

onDragOver :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragOver :: DragEvent | r)
onDragOver = eventProp "onDragOver"

onDragStart :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragStart :: DragEvent | r)
onDragStart = eventProp "onDragStart"

onDrop :: forall r. (DragEvent -> Effect Unit) -> Prop (onDrop :: DragEvent | r)
onDrop = eventProp "onDrop"

onDurationChange :: forall r. (Event -> Effect Unit) -> Prop (onDurationChange :: Event | r)
onDurationChange = eventProp "onDurationChange"

onEmptied :: forall r. (Event -> Effect Unit) -> Prop (onEmptied :: Event | r)
onEmptied = eventProp "onEmptied"

onEnded :: forall r. (Event -> Effect Unit) -> Prop (onEnded :: Event | r)
onEnded = eventProp "onEnded"

onError :: forall r. (Event -> Effect Unit) -> Prop (onError :: Event | r)
onError = eventProp "onError"

onFocus :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocus :: FocusEvent | r)
onFocus = eventProp "onFocus"

onFocusIn :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocusIn :: FocusEvent | r)
onFocusIn = eventProp "onFocusIn"

onFocusOut :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocusOut :: FocusEvent | r)
onFocusOut = eventProp "onFocusOut"

onGotPointerCapture :: forall r. (PointerEvent -> Effect Unit) -> Prop (onGotPointerCapture :: PointerEvent | r)
onGotPointerCapture = eventProp "onGotPointerCapture"

onHashChange :: forall r. (Event -> Effect Unit) -> Prop (onHashChange :: Event | r)
onHashChange = eventProp "onHashChange"

onInput :: forall r. (Event -> Effect Unit) -> Prop (onInput :: Event | r)
onInput = eventProp "onInput"

onInvalid :: forall r. (Event -> Effect Unit) -> Prop (onInvalid :: Event | r)
onInvalid = eventProp "onInvalid"

onKeyDown :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyDown :: KeyboardEvent | r)
onKeyDown = eventProp "onKeyDown"

onKeyPress :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyPress :: KeyboardEvent | r)
onKeyPress = eventProp "onKeyPress"

onKeyUp :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyUp :: KeyboardEvent | r)
onKeyUp = eventProp "onKeyUp"

onLoad :: forall r. (Event -> Effect Unit) -> Prop (onLoad :: Event | r)
onLoad = eventProp "onLoad"

onLoadStart :: forall r. (Event -> Effect Unit) -> Prop (onLoadStart :: Event | r)
onLoadStart = eventProp "onLoadStart"

onLoadedData :: forall r. (Event -> Effect Unit) -> Prop (onLoadedData :: Event | r)
onLoadedData = eventProp "onLoadedData"

onLoadedMetadata :: forall r. (Event -> Effect Unit) -> Prop (onLoadedMetadata :: Event | r)
onLoadedMetadata = eventProp "onLoadedMetadata"

onLostPointerCapture :: forall r. (PointerEvent -> Effect Unit) -> Prop (onLostPointerCapture :: PointerEvent | r)
onLostPointerCapture = eventProp "onLostPointerCapture"

onMouseDown :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseDown :: MouseEvent | r)
onMouseDown = eventProp "onMouseDown"

onMouseEnter :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseEnter :: MouseEvent | r)
onMouseEnter = eventProp "onMouseEnter"

onMouseLeave :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseLeave :: MouseEvent | r)
onMouseLeave = eventProp "onMouseLeave"

onMouseMove :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseMove :: MouseEvent | r)
onMouseMove = eventProp "onMouseMove"

onMouseOut :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseOut :: MouseEvent | r)
onMouseOut = eventProp "onMouseOut"

onMouseOver :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseOver :: MouseEvent | r)
onMouseOver = eventProp "onMouseOver"

onMouseUp :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseUp :: MouseEvent | r)
onMouseUp = eventProp "onMouseUp"

onPageHide :: forall r. (Event -> Effect Unit) -> Prop (onPageHide :: Event | r)
onPageHide = eventProp "onPageHide"

onPageShow :: forall r. (Event -> Effect Unit) -> Prop (onPageShow :: Event | r)
onPageShow = eventProp "onPageShow"

onPaste :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onPaste :: ClipboardEvent | r)
onPaste = eventProp "onPaste"

onPause :: forall r. (Event -> Effect Unit) -> Prop (onPause :: Event | r)
onPause = eventProp "onPause"

onPlay :: forall r. (Event -> Effect Unit) -> Prop (onPlay :: Event | r)
onPlay = eventProp "onPlay"

onPlaying :: forall r. (Event -> Effect Unit) -> Prop (onPlaying :: Event | r)
onPlaying = eventProp "onPlaying"

onPointerCancel :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerCancel :: PointerEvent | r)
onPointerCancel = eventProp "onPointerCancel"

onPointerDown :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerDown :: PointerEvent | r)
onPointerDown = eventProp "onPointerDown"

onPointerEnter :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerEnter :: PointerEvent | r)
onPointerEnter = eventProp "onPointerEnter"

onPointerLeave :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerLeave :: PointerEvent | r)
onPointerLeave = eventProp "onPointerLeave"

onPointerMove :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerMove :: PointerEvent | r)
onPointerMove = eventProp "onPointerMove"

onPointerOut :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerOut :: PointerEvent | r)
onPointerOut = eventProp "onPointerOut"

onPointerOver :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerOver :: PointerEvent | r)
onPointerOver = eventProp "onPointerOver"

onPointerUp :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerUp :: PointerEvent | r)
onPointerUp = eventProp "onPointerUp"

onProgress :: forall r. (Event -> Effect Unit) -> Prop (onProgress :: Event | r)
onProgress = eventProp "onProgress"

onRateChange :: forall r. (Event -> Effect Unit) -> Prop (onRateChange :: Event | r)
onRateChange = eventProp "onRateChange"

onReset :: forall r. (Event -> Effect Unit) -> Prop (onReset :: Event | r)
onReset = eventProp "onReset"

onResize :: forall r. (Event -> Effect Unit) -> Prop (onResize :: Event | r)
onResize = eventProp "onResize"

onScroll :: forall r. (Event -> Effect Unit) -> Prop (onScroll :: Event | r)
onScroll = eventProp "onScroll"

onSearch :: forall r. (Event -> Effect Unit) -> Prop (onSearch :: Event | r)
onSearch = eventProp "onSearch"

onSeeked :: forall r. (Event -> Effect Unit) -> Prop (onSeeked :: Event | r)
onSeeked = eventProp "onSeeked"

onSeeking :: forall r. (Event -> Effect Unit) -> Prop (onSeeking :: Event | r)
onSeeking = eventProp "onSeeking"

onSelect :: forall r. (Event -> Effect Unit) -> Prop (onSelect :: Event | r)
onSelect = eventProp "onSelect"

onStalled :: forall r. (Event -> Effect Unit) -> Prop (onStalled :: Event | r)
onStalled = eventProp "onStalled"

onSubmit :: forall r. (Event -> Effect Unit) -> Prop (onSubmit :: Event | r)
onSubmit = eventProp "onSubmit"

onSuspend :: forall r. (Event -> Effect Unit) -> Prop (onSuspend :: Event | r)
onSuspend = eventProp "onSuspend"

onTimeUpdate :: forall r. (Event -> Effect Unit) -> Prop (onTimeUpdate :: Event | r)
onTimeUpdate = eventProp "onTimeUpdate"

onTouchCancel :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchCancel :: TouchEvent | r)
onTouchCancel = eventProp "onTouchCancel"

onTouchEnd :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchEnd :: TouchEvent | r)
onTouchEnd = eventProp "onTouchEnd"

onTouchEnter :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchEnter :: TouchEvent | r)
onTouchEnter = eventProp "onTouchEnter"

onTouchLeave :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchLeave :: TouchEvent | r)
onTouchLeave = eventProp "onTouchLeave"

onTouchMove :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchMove :: TouchEvent | r)
onTouchMove = eventProp "onTouchMove"

onTouchStart :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchStart :: TouchEvent | r)
onTouchStart = eventProp "onTouchStart"

onTransitionEnd :: forall r. (Event -> Effect Unit) -> Prop (onTransitionEnd :: Event | r)
onTransitionEnd = eventProp "onTransitionEnd"

onUnload :: forall r. (Event -> Effect Unit) -> Prop (onUnload :: Event | r)
onUnload = eventProp "onUnload"

onVolumeChange :: forall r. (Event -> Effect Unit) -> Prop (onVolumeChange :: Event | r)
onVolumeChange = eventProp "onVolumeChange"

onWaiting :: forall r. (Event -> Effect Unit) -> Prop (onWaiting :: Event | r)
onWaiting = eventProp "onWaiting"

onWheel :: forall r. (WheelEvent -> Effect Unit) -> Prop (onWheel :: WheelEvent | r)
onWheel = eventProp "onWheel"

open :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (open :: a | r)
open v = bindingProp "open" toAttrValue (binding v)

optimum :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (optimum :: a | r)
optimum v = bindingProp "optimum" toAttrValue (binding v)

pattern :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pattern :: a | r)
pattern v = bindingProp "pattern" toAttrValue (binding v)

placeholder :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (placeholder :: a | r)
placeholder v = bindingProp "placeholder" toAttrValue (binding v)

poster :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (poster :: a | r)
poster v = bindingProp "poster" toAttrValue (binding v)

preload :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (preload :: a | r)
preload v = bindingProp "preload" toAttrValue (binding v)

radioGroup :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (radioGroup :: a | r)
radioGroup v = bindingProp "radiogroup" toAttrValue (binding v)

readOnly :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (readOnly :: a | r)
readOnly v = bindingProp "readonly" toAttrValue (binding v)

rel :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rel :: a | r)
rel v = bindingProp "rel" toAttrValue (binding v)

required :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (required :: a | r)
required v = bindingProp "required" toAttrValue (binding v)

reversed :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (reversed :: a | r)
reversed v = bindingProp "reversed" toAttrValue (binding v)

rowSpan :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rowSpan :: a | r)
rowSpan v = bindingProp "rowspan" toAttrValue (binding v)

rows :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rows :: a | r)
rows v = bindingProp "rows" toAttrValue (binding v)

sandbox :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sandbox :: a | r)
sandbox v = bindingProp "sandbox" toAttrValue (binding v)

scope :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (scope :: a | r)
scope v = bindingProp "scope" toAttrValue (binding v)

scoped :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (scoped :: a | r)
scoped v = bindingProp "scoped" toAttrValue (binding v)

selected :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (selected :: a | r)
selected v = bindingProp "selected" toAttrValue (binding v)

selectedIndex :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (selectedIndex :: a | r)
selectedIndex v = bindingProp "selectedindex" toAttrValue (binding v)

shape :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (shape :: a | r)
shape v = bindingProp "shape" toAttrValue (binding v)

size :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (size :: a | r)
size v = bindingProp "size" toAttrValue (binding v)

sizes :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sizes :: a | r)
sizes v = bindingProp "sizes" toAttrValue (binding v)

sortable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sortable :: a | r)
sortable v = bindingProp "sortable" toAttrValue (binding v)

sorted :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sorted :: a | r)
sorted v = bindingProp "sorted" toAttrValue (binding v)

span :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (span :: a | r)
span v = bindingProp "span" toAttrValue (binding v)

spellcheck :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (spellcheck :: a | r)
spellcheck v = bindingProp "spellcheck" toAttrValue (binding v)

src :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (src :: a | r)
src v = bindingProp "src" toAttrValue (binding v)

srcDoc :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (srcDoc :: a | r)
srcDoc v = bindingProp "srcdoc" toAttrValue (binding v)

srcLang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (srcLang :: a | r)
srcLang v = bindingProp "srclang" toAttrValue (binding v)

start :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (start :: a | r)
start v = bindingProp "start" toAttrValue (binding v)

step :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (step :: a | r)
step v = bindingProp "step" toAttrValue (binding v)

style :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (style :: a | r)
style v = bindingProp "style" toAttrValue (binding v)

tabIndex :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (tabIndex :: a | r)
tabIndex v = bindingProp "tabindex" toAttrValue (binding v)

target :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (target :: a | r)
target v = bindingProp "target" toAttrValue (binding v)

title :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (title :: a | r)
title v = bindingProp "title" toAttrValue (binding v)

type_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (type :: a | r)
type_ v = bindingProp "type" toAttrValue (binding v)

useMap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (useMap :: a | r)
useMap v = bindingProp "usemap" toAttrValue (binding v)

value :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (value :: a | r)
value v = bindingProp "value" toAttrValue (binding v)

width :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (width :: a | r)
width v = bindingProp "width" toAttrValue (binding v)

wrap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (wrap :: a | r)
wrap v = bindingProp "wrap" toAttrValue (binding v)

xmlns :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (xmlns :: a | r)
xmlns v = bindingProp "xmlns" toAttrValue (binding v)
