-- | Typed element properties. Each helper only type-checks on elements that
-- | support it, with the value type the element declares. Values may be
-- | fixed or `Accessor`s (reactive).
-- |
-- | Generated by `scripts/gen-dom.mjs` from `dom-indexed`; do not edit.
module Solid.DOM.Props
  ( abbr
  , accept
  , acceptCharset
  , accessKey
  , action
  , alt
  , async
  , autocomplete
  , autofocus
  , autoplay
  , charset
  , checked
  , cite
  , class_
  , colSpan
  , cols
  , command
  , content
  , contentEditable
  , controls
  , coords
  , crossOrigin
  , data_
  , datetime
  , default
  , defer
  , dir
  , disabled
  , download
  , draggable
  , enctype
  , for
  , form
  , formAction
  , formEncType
  , formMethod
  , formNoValidate
  , formTarget
  , headers
  , height
  , hidden
  , high
  , href
  , hrefLang
  , hreflang
  , httpEquiv
  , icon
  , id
  , isMap
  , kind
  , label
  , lang
  , list
  , longDesc
  , loop
  , low
  , manifest
  , max
  , maxLength
  , media
  , method
  , min
  , minLength
  , multiple
  , muted
  , name
  , noValidate
  , onAbort
  , onAuxClick
  , onBeforeInput
  , onBeforeUnload
  , onBlur
  , onCanPlay
  , onCanPlayThrough
  , onChange
  , onClick
  , onContextMenu
  , onCopy
  , onCut
  , onDoubleClick
  , onDrag
  , onDragEnd
  , onDragEnter
  , onDragExit
  , onDragLeave
  , onDragOver
  , onDragStart
  , onDrop
  , onDurationChange
  , onEmptied
  , onEnded
  , onError
  , onFocus
  , onFocusIn
  , onFocusOut
  , onGotPointerCapture
  , onHashChange
  , onInput
  , onInvalid
  , onKeyDown
  , onKeyPress
  , onKeyUp
  , onLoad
  , onLoadStart
  , onLoadedData
  , onLoadedMetadata
  , onLostPointerCapture
  , onMouseDown
  , onMouseEnter
  , onMouseLeave
  , onMouseMove
  , onMouseOut
  , onMouseOver
  , onMouseUp
  , onPageHide
  , onPageShow
  , onPaste
  , onPause
  , onPlay
  , onPlaying
  , onPointerCancel
  , onPointerDown
  , onPointerEnter
  , onPointerLeave
  , onPointerMove
  , onPointerOut
  , onPointerOver
  , onPointerUp
  , onProgress
  , onRateChange
  , onReset
  , onResize
  , onScroll
  , onSearch
  , onSeeked
  , onSeeking
  , onSelect
  , onStalled
  , onSubmit
  , onSuspend
  , onTimeUpdate
  , onTouchCancel
  , onTouchEnd
  , onTouchEnter
  , onTouchLeave
  , onTouchMove
  , onTouchStart
  , onTransitionEnd
  , onUnload
  , onVolumeChange
  , onWaiting
  , onWheel
  , open
  , optimum
  , pattern
  , placeholder
  , poster
  , preload
  , radioGroup
  , readOnly
  , rel
  , required
  , reversed
  , rowSpan
  , rows
  , sandbox
  , scope
  , scoped
  , selected
  , selectedIndex
  , shape
  , size
  , sizes
  , sortable
  , sorted
  , span
  , spellcheck
  , src
  , srcDoc
  , srcLang
  , start
  , step
  , style
  , tabIndex
  , target
  , title
  , type_
  , useMap
  , value
  , width
  , wrap
  , xmlns
  ) where

import Prelude

import Web.Clipboard.ClipboardEvent (ClipboardEvent)
import Web.HTML.Event.DragEvent (DragEvent)
import Web.Event.Event (Event)
import Web.UIEvent.FocusEvent (FocusEvent)
import Web.UIEvent.KeyboardEvent (KeyboardEvent)
import Web.UIEvent.MouseEvent (MouseEvent)
import Web.PointerEvent (PointerEvent)
import Web.TouchEvent (TouchEvent)
import Web.UIEvent.WheelEvent (WheelEvent)
import Solid.DOM.AttrValue (class AttrValue, toAttrValue)
import Solid.Internal.View (class ToBinding, Prop, binding, bindingProp, eventProp)
import Effect (Effect)

abbr :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (abbr :: a | r)
abbr value = bindingProp "abbr" toAttrValue (binding value)

accept :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (accept :: a | r)
accept value = bindingProp "accept" toAttrValue (binding value)

acceptCharset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (acceptCharset :: a | r)
acceptCharset value = bindingProp "accept-charset" toAttrValue (binding value)

accessKey :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (accessKey :: a | r)
accessKey value = bindingProp "accesskey" toAttrValue (binding value)

action :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (action :: a | r)
action value = bindingProp "action" toAttrValue (binding value)

alt :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (alt :: a | r)
alt value = bindingProp "alt" toAttrValue (binding value)

async :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (async :: a | r)
async value = bindingProp "async" toAttrValue (binding value)

autocomplete :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autocomplete :: a | r)
autocomplete value = bindingProp "autocomplete" toAttrValue (binding value)

autofocus :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autofocus :: a | r)
autofocus value = bindingProp "autofocus" toAttrValue (binding value)

autoplay :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (autoplay :: a | r)
autoplay value = bindingProp "autoplay" toAttrValue (binding value)

charset :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (charset :: a | r)
charset value = bindingProp "charset" toAttrValue (binding value)

checked :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (checked :: a | r)
checked value = bindingProp "checked" toAttrValue (binding value)

cite :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cite :: a | r)
cite value = bindingProp "cite" toAttrValue (binding value)

class_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (class :: a | r)
class_ value = bindingProp "class" toAttrValue (binding value)

colSpan :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (colSpan :: a | r)
colSpan value = bindingProp "colspan" toAttrValue (binding value)

cols :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (cols :: a | r)
cols value = bindingProp "cols" toAttrValue (binding value)

command :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (command :: a | r)
command value = bindingProp "command" toAttrValue (binding value)

content :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (content :: a | r)
content value = bindingProp "content" toAttrValue (binding value)

contentEditable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (contentEditable :: a | r)
contentEditable value = bindingProp "contenteditable" toAttrValue (binding value)

controls :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (controls :: a | r)
controls value = bindingProp "controls" toAttrValue (binding value)

coords :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (coords :: a | r)
coords value = bindingProp "coords" toAttrValue (binding value)

crossOrigin :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (crossOrigin :: a | r)
crossOrigin value = bindingProp "crossorigin" toAttrValue (binding value)

data_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (data :: a | r)
data_ value = bindingProp "data" toAttrValue (binding value)

datetime :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (datetime :: a | r)
datetime value = bindingProp "datetime" toAttrValue (binding value)

default :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (default :: a | r)
default value = bindingProp "default" toAttrValue (binding value)

defer :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (defer :: a | r)
defer value = bindingProp "defer" toAttrValue (binding value)

dir :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (dir :: a | r)
dir value = bindingProp "dir" toAttrValue (binding value)

disabled :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (disabled :: a | r)
disabled value = bindingProp "disabled" toAttrValue (binding value)

download :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (download :: a | r)
download value = bindingProp "download" toAttrValue (binding value)

draggable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (draggable :: a | r)
draggable value = bindingProp "draggable" toAttrValue (binding value)

enctype :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (enctype :: a | r)
enctype value = bindingProp "enctype" toAttrValue (binding value)

for :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (for :: a | r)
for value = bindingProp "for" toAttrValue (binding value)

form :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (form :: a | r)
form value = bindingProp "form" toAttrValue (binding value)

formAction :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formAction :: a | r)
formAction value = bindingProp "formaction" toAttrValue (binding value)

formEncType :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formEncType :: a | r)
formEncType value = bindingProp "formenctype" toAttrValue (binding value)

formMethod :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formMethod :: a | r)
formMethod value = bindingProp "formmethod" toAttrValue (binding value)

formNoValidate :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formNoValidate :: a | r)
formNoValidate value = bindingProp "formnovalidate" toAttrValue (binding value)

formTarget :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (formTarget :: a | r)
formTarget value = bindingProp "formtarget" toAttrValue (binding value)

headers :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (headers :: a | r)
headers value = bindingProp "headers" toAttrValue (binding value)

height :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (height :: a | r)
height value = bindingProp "height" toAttrValue (binding value)

hidden :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hidden :: a | r)
hidden value = bindingProp "hidden" toAttrValue (binding value)

high :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (high :: a | r)
high value = bindingProp "high" toAttrValue (binding value)

href :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (href :: a | r)
href value = bindingProp "href" toAttrValue (binding value)

hrefLang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hrefLang :: a | r)
hrefLang value = bindingProp "hreflang" toAttrValue (binding value)

hreflang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (hreflang :: a | r)
hreflang value = bindingProp "hreflang" toAttrValue (binding value)

httpEquiv :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (httpEquiv :: a | r)
httpEquiv value = bindingProp "http-equiv" toAttrValue (binding value)

icon :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (icon :: a | r)
icon value = bindingProp "icon" toAttrValue (binding value)

id :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (id :: a | r)
id value = bindingProp "id" toAttrValue (binding value)

isMap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (isMap :: a | r)
isMap value = bindingProp "ismap" toAttrValue (binding value)

kind :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (kind :: a | r)
kind value = bindingProp "kind" toAttrValue (binding value)

label :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (label :: a | r)
label value = bindingProp "label" toAttrValue (binding value)

lang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (lang :: a | r)
lang value = bindingProp "lang" toAttrValue (binding value)

list :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (list :: a | r)
list value = bindingProp "list" toAttrValue (binding value)

longDesc :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (longDesc :: a | r)
longDesc value = bindingProp "longdesc" toAttrValue (binding value)

loop :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (loop :: a | r)
loop value = bindingProp "loop" toAttrValue (binding value)

low :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (low :: a | r)
low value = bindingProp "low" toAttrValue (binding value)

manifest :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (manifest :: a | r)
manifest value = bindingProp "manifest" toAttrValue (binding value)

max :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (max :: a | r)
max value = bindingProp "max" toAttrValue (binding value)

maxLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (maxLength :: a | r)
maxLength value = bindingProp "maxlength" toAttrValue (binding value)

media :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (media :: a | r)
media value = bindingProp "media" toAttrValue (binding value)

method :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (method :: a | r)
method value = bindingProp "method" toAttrValue (binding value)

min :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (min :: a | r)
min value = bindingProp "min" toAttrValue (binding value)

minLength :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (minLength :: a | r)
minLength value = bindingProp "minlength" toAttrValue (binding value)

multiple :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (multiple :: a | r)
multiple value = bindingProp "multiple" toAttrValue (binding value)

muted :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (muted :: a | r)
muted value = bindingProp "muted" toAttrValue (binding value)

name :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (name :: a | r)
name value = bindingProp "name" toAttrValue (binding value)

noValidate :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (noValidate :: a | r)
noValidate value = bindingProp "novalidate" toAttrValue (binding value)

onAbort :: forall r. (Event -> Effect Unit) -> Prop (onAbort :: Event | r)
onAbort = eventProp "onAbort"

onAuxClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onAuxClick :: MouseEvent | r)
onAuxClick = eventProp "onAuxClick"

onBeforeInput :: forall r. (Event -> Effect Unit) -> Prop (onBeforeInput :: Event | r)
onBeforeInput = eventProp "onBeforeInput"

onBeforeUnload :: forall r. (Event -> Effect Unit) -> Prop (onBeforeUnload :: Event | r)
onBeforeUnload = eventProp "onBeforeUnload"

onBlur :: forall r. (FocusEvent -> Effect Unit) -> Prop (onBlur :: FocusEvent | r)
onBlur = eventProp "onBlur"

onCanPlay :: forall r. (Event -> Effect Unit) -> Prop (onCanPlay :: Event | r)
onCanPlay = eventProp "onCanPlay"

onCanPlayThrough :: forall r. (Event -> Effect Unit) -> Prop (onCanPlayThrough :: Event | r)
onCanPlayThrough = eventProp "onCanPlayThrough"

onChange :: forall r. (Event -> Effect Unit) -> Prop (onChange :: Event | r)
onChange = eventProp "onChange"

onClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onClick :: MouseEvent | r)
onClick = eventProp "onClick"

onContextMenu :: forall r. (Event -> Effect Unit) -> Prop (onContextMenu :: Event | r)
onContextMenu = eventProp "onContextMenu"

onCopy :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onCopy :: ClipboardEvent | r)
onCopy = eventProp "onCopy"

onCut :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onCut :: ClipboardEvent | r)
onCut = eventProp "onCut"

onDoubleClick :: forall r. (MouseEvent -> Effect Unit) -> Prop (onDoubleClick :: MouseEvent | r)
onDoubleClick = eventProp "onDblClick"

onDrag :: forall r. (DragEvent -> Effect Unit) -> Prop (onDrag :: DragEvent | r)
onDrag = eventProp "onDrag"

onDragEnd :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragEnd :: DragEvent | r)
onDragEnd = eventProp "onDragEnd"

onDragEnter :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragEnter :: DragEvent | r)
onDragEnter = eventProp "onDragEnter"

onDragExit :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragExit :: DragEvent | r)
onDragExit = eventProp "onDragExit"

onDragLeave :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragLeave :: DragEvent | r)
onDragLeave = eventProp "onDragLeave"

onDragOver :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragOver :: DragEvent | r)
onDragOver = eventProp "onDragOver"

onDragStart :: forall r. (DragEvent -> Effect Unit) -> Prop (onDragStart :: DragEvent | r)
onDragStart = eventProp "onDragStart"

onDrop :: forall r. (DragEvent -> Effect Unit) -> Prop (onDrop :: DragEvent | r)
onDrop = eventProp "onDrop"

onDurationChange :: forall r. (Event -> Effect Unit) -> Prop (onDurationChange :: Event | r)
onDurationChange = eventProp "onDurationChange"

onEmptied :: forall r. (Event -> Effect Unit) -> Prop (onEmptied :: Event | r)
onEmptied = eventProp "onEmptied"

onEnded :: forall r. (Event -> Effect Unit) -> Prop (onEnded :: Event | r)
onEnded = eventProp "onEnded"

onError :: forall r. (Event -> Effect Unit) -> Prop (onError :: Event | r)
onError = eventProp "onError"

onFocus :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocus :: FocusEvent | r)
onFocus = eventProp "onFocus"

onFocusIn :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocusIn :: FocusEvent | r)
onFocusIn = eventProp "onFocusIn"

onFocusOut :: forall r. (FocusEvent -> Effect Unit) -> Prop (onFocusOut :: FocusEvent | r)
onFocusOut = eventProp "onFocusOut"

onGotPointerCapture :: forall r. (PointerEvent -> Effect Unit) -> Prop (onGotPointerCapture :: PointerEvent | r)
onGotPointerCapture = eventProp "onGotPointerCapture"

onHashChange :: forall r. (Event -> Effect Unit) -> Prop (onHashChange :: Event | r)
onHashChange = eventProp "onHashChange"

onInput :: forall r. (Event -> Effect Unit) -> Prop (onInput :: Event | r)
onInput = eventProp "onInput"

onInvalid :: forall r. (Event -> Effect Unit) -> Prop (onInvalid :: Event | r)
onInvalid = eventProp "onInvalid"

onKeyDown :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyDown :: KeyboardEvent | r)
onKeyDown = eventProp "onKeyDown"

onKeyPress :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyPress :: KeyboardEvent | r)
onKeyPress = eventProp "onKeyPress"

onKeyUp :: forall r. (KeyboardEvent -> Effect Unit) -> Prop (onKeyUp :: KeyboardEvent | r)
onKeyUp = eventProp "onKeyUp"

onLoad :: forall r. (Event -> Effect Unit) -> Prop (onLoad :: Event | r)
onLoad = eventProp "onLoad"

onLoadStart :: forall r. (Event -> Effect Unit) -> Prop (onLoadStart :: Event | r)
onLoadStart = eventProp "onLoadStart"

onLoadedData :: forall r. (Event -> Effect Unit) -> Prop (onLoadedData :: Event | r)
onLoadedData = eventProp "onLoadedData"

onLoadedMetadata :: forall r. (Event -> Effect Unit) -> Prop (onLoadedMetadata :: Event | r)
onLoadedMetadata = eventProp "onLoadedMetadata"

onLostPointerCapture :: forall r. (PointerEvent -> Effect Unit) -> Prop (onLostPointerCapture :: PointerEvent | r)
onLostPointerCapture = eventProp "onLostPointerCapture"

onMouseDown :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseDown :: MouseEvent | r)
onMouseDown = eventProp "onMouseDown"

onMouseEnter :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseEnter :: MouseEvent | r)
onMouseEnter = eventProp "onMouseEnter"

onMouseLeave :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseLeave :: MouseEvent | r)
onMouseLeave = eventProp "onMouseLeave"

onMouseMove :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseMove :: MouseEvent | r)
onMouseMove = eventProp "onMouseMove"

onMouseOut :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseOut :: MouseEvent | r)
onMouseOut = eventProp "onMouseOut"

onMouseOver :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseOver :: MouseEvent | r)
onMouseOver = eventProp "onMouseOver"

onMouseUp :: forall r. (MouseEvent -> Effect Unit) -> Prop (onMouseUp :: MouseEvent | r)
onMouseUp = eventProp "onMouseUp"

onPageHide :: forall r. (Event -> Effect Unit) -> Prop (onPageHide :: Event | r)
onPageHide = eventProp "onPageHide"

onPageShow :: forall r. (Event -> Effect Unit) -> Prop (onPageShow :: Event | r)
onPageShow = eventProp "onPageShow"

onPaste :: forall r. (ClipboardEvent -> Effect Unit) -> Prop (onPaste :: ClipboardEvent | r)
onPaste = eventProp "onPaste"

onPause :: forall r. (Event -> Effect Unit) -> Prop (onPause :: Event | r)
onPause = eventProp "onPause"

onPlay :: forall r. (Event -> Effect Unit) -> Prop (onPlay :: Event | r)
onPlay = eventProp "onPlay"

onPlaying :: forall r. (Event -> Effect Unit) -> Prop (onPlaying :: Event | r)
onPlaying = eventProp "onPlaying"

onPointerCancel :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerCancel :: PointerEvent | r)
onPointerCancel = eventProp "onPointerCancel"

onPointerDown :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerDown :: PointerEvent | r)
onPointerDown = eventProp "onPointerDown"

onPointerEnter :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerEnter :: PointerEvent | r)
onPointerEnter = eventProp "onPointerEnter"

onPointerLeave :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerLeave :: PointerEvent | r)
onPointerLeave = eventProp "onPointerLeave"

onPointerMove :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerMove :: PointerEvent | r)
onPointerMove = eventProp "onPointerMove"

onPointerOut :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerOut :: PointerEvent | r)
onPointerOut = eventProp "onPointerOut"

onPointerOver :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerOver :: PointerEvent | r)
onPointerOver = eventProp "onPointerOver"

onPointerUp :: forall r. (PointerEvent -> Effect Unit) -> Prop (onPointerUp :: PointerEvent | r)
onPointerUp = eventProp "onPointerUp"

onProgress :: forall r. (Event -> Effect Unit) -> Prop (onProgress :: Event | r)
onProgress = eventProp "onProgress"

onRateChange :: forall r. (Event -> Effect Unit) -> Prop (onRateChange :: Event | r)
onRateChange = eventProp "onRateChange"

onReset :: forall r. (Event -> Effect Unit) -> Prop (onReset :: Event | r)
onReset = eventProp "onReset"

onResize :: forall r. (Event -> Effect Unit) -> Prop (onResize :: Event | r)
onResize = eventProp "onResize"

onScroll :: forall r. (Event -> Effect Unit) -> Prop (onScroll :: Event | r)
onScroll = eventProp "onScroll"

onSearch :: forall r. (Event -> Effect Unit) -> Prop (onSearch :: Event | r)
onSearch = eventProp "onSearch"

onSeeked :: forall r. (Event -> Effect Unit) -> Prop (onSeeked :: Event | r)
onSeeked = eventProp "onSeeked"

onSeeking :: forall r. (Event -> Effect Unit) -> Prop (onSeeking :: Event | r)
onSeeking = eventProp "onSeeking"

onSelect :: forall r. (Event -> Effect Unit) -> Prop (onSelect :: Event | r)
onSelect = eventProp "onSelect"

onStalled :: forall r. (Event -> Effect Unit) -> Prop (onStalled :: Event | r)
onStalled = eventProp "onStalled"

onSubmit :: forall r. (Event -> Effect Unit) -> Prop (onSubmit :: Event | r)
onSubmit = eventProp "onSubmit"

onSuspend :: forall r. (Event -> Effect Unit) -> Prop (onSuspend :: Event | r)
onSuspend = eventProp "onSuspend"

onTimeUpdate :: forall r. (Event -> Effect Unit) -> Prop (onTimeUpdate :: Event | r)
onTimeUpdate = eventProp "onTimeUpdate"

onTouchCancel :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchCancel :: TouchEvent | r)
onTouchCancel = eventProp "onTouchCancel"

onTouchEnd :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchEnd :: TouchEvent | r)
onTouchEnd = eventProp "onTouchEnd"

onTouchEnter :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchEnter :: TouchEvent | r)
onTouchEnter = eventProp "onTouchEnter"

onTouchLeave :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchLeave :: TouchEvent | r)
onTouchLeave = eventProp "onTouchLeave"

onTouchMove :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchMove :: TouchEvent | r)
onTouchMove = eventProp "onTouchMove"

onTouchStart :: forall r. (TouchEvent -> Effect Unit) -> Prop (onTouchStart :: TouchEvent | r)
onTouchStart = eventProp "onTouchStart"

onTransitionEnd :: forall r. (Event -> Effect Unit) -> Prop (onTransitionEnd :: Event | r)
onTransitionEnd = eventProp "onTransitionEnd"

onUnload :: forall r. (Event -> Effect Unit) -> Prop (onUnload :: Event | r)
onUnload = eventProp "onUnload"

onVolumeChange :: forall r. (Event -> Effect Unit) -> Prop (onVolumeChange :: Event | r)
onVolumeChange = eventProp "onVolumeChange"

onWaiting :: forall r. (Event -> Effect Unit) -> Prop (onWaiting :: Event | r)
onWaiting = eventProp "onWaiting"

onWheel :: forall r. (WheelEvent -> Effect Unit) -> Prop (onWheel :: WheelEvent | r)
onWheel = eventProp "onWheel"

open :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (open :: a | r)
open value = bindingProp "open" toAttrValue (binding value)

optimum :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (optimum :: a | r)
optimum value = bindingProp "optimum" toAttrValue (binding value)

pattern :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (pattern :: a | r)
pattern value = bindingProp "pattern" toAttrValue (binding value)

placeholder :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (placeholder :: a | r)
placeholder value = bindingProp "placeholder" toAttrValue (binding value)

poster :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (poster :: a | r)
poster value = bindingProp "poster" toAttrValue (binding value)

preload :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (preload :: a | r)
preload value = bindingProp "preload" toAttrValue (binding value)

radioGroup :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (radioGroup :: a | r)
radioGroup value = bindingProp "radiogroup" toAttrValue (binding value)

readOnly :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (readOnly :: a | r)
readOnly value = bindingProp "readonly" toAttrValue (binding value)

rel :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rel :: a | r)
rel value = bindingProp "rel" toAttrValue (binding value)

required :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (required :: a | r)
required value = bindingProp "required" toAttrValue (binding value)

reversed :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (reversed :: a | r)
reversed value = bindingProp "reversed" toAttrValue (binding value)

rowSpan :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rowSpan :: a | r)
rowSpan value = bindingProp "rowspan" toAttrValue (binding value)

rows :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (rows :: a | r)
rows value = bindingProp "rows" toAttrValue (binding value)

sandbox :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sandbox :: a | r)
sandbox value = bindingProp "sandbox" toAttrValue (binding value)

scope :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (scope :: a | r)
scope value = bindingProp "scope" toAttrValue (binding value)

scoped :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (scoped :: a | r)
scoped value = bindingProp "scoped" toAttrValue (binding value)

selected :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (selected :: a | r)
selected value = bindingProp "selected" toAttrValue (binding value)

selectedIndex :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (selectedIndex :: a | r)
selectedIndex value = bindingProp "selectedindex" toAttrValue (binding value)

shape :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (shape :: a | r)
shape value = bindingProp "shape" toAttrValue (binding value)

size :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (size :: a | r)
size value = bindingProp "size" toAttrValue (binding value)

sizes :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sizes :: a | r)
sizes value = bindingProp "sizes" toAttrValue (binding value)

sortable :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sortable :: a | r)
sortable value = bindingProp "sortable" toAttrValue (binding value)

sorted :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (sorted :: a | r)
sorted value = bindingProp "sorted" toAttrValue (binding value)

span :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (span :: a | r)
span value = bindingProp "span" toAttrValue (binding value)

spellcheck :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (spellcheck :: a | r)
spellcheck value = bindingProp "spellcheck" toAttrValue (binding value)

src :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (src :: a | r)
src value = bindingProp "src" toAttrValue (binding value)

srcDoc :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (srcDoc :: a | r)
srcDoc value = bindingProp "srcdoc" toAttrValue (binding value)

srcLang :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (srcLang :: a | r)
srcLang value = bindingProp "srclang" toAttrValue (binding value)

start :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (start :: a | r)
start value = bindingProp "start" toAttrValue (binding value)

step :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (step :: a | r)
step value = bindingProp "step" toAttrValue (binding value)

style :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (style :: a | r)
style value = bindingProp "style" toAttrValue (binding value)

tabIndex :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (tabIndex :: a | r)
tabIndex value = bindingProp "tabindex" toAttrValue (binding value)

target :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (target :: a | r)
target value = bindingProp "target" toAttrValue (binding value)

title :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (title :: a | r)
title value = bindingProp "title" toAttrValue (binding value)

type_ :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (type :: a | r)
type_ value = bindingProp "type" toAttrValue (binding value)

useMap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (useMap :: a | r)
useMap value = bindingProp "usemap" toAttrValue (binding value)

value :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (value :: a | r)
value value = bindingProp "value" toAttrValue (binding value)

width :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (width :: a | r)
width value = bindingProp "width" toAttrValue (binding value)

wrap :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (wrap :: a | r)
wrap value = bindingProp "wrap" toAttrValue (binding value)

xmlns :: forall r v a. ToBinding v a => AttrValue a => v -> Prop (xmlns :: a | r)
xmlns value = bindingProp "xmlns" toAttrValue (binding value)
