-- | SVG elements. Generated by `scripts/gen-dom.mjs`.
module Solid.DOM.SVG where

import DOM.HTML.Indexed as I
import Solid.Internal.Props (class Children, class Props, typedElement)
import Solid.Internal.View (JSX, svgNamespace)
import Web.DOM.Element (Element)

type SVGAttributes = I.InteractiveEvents
  ( "$element" :: Element
  , class :: String
  , height :: String
  , href :: String
  , id :: String
  , lang :: String
  , style :: String
  , tabIndex :: Int
  , width :: String
  , clipPath :: String
  , clipRule :: String
  , cx :: String
  , cy :: String
  , d :: String
  , display :: String
  , dominantBaseline :: String
  , dx :: String
  , dy :: String
  , fill :: String
  , fillOpacity :: String
  , fillRule :: String
  , filter :: String
  , fontFamily :: String
  , fontSize :: String
  , fontWeight :: String
  , fx :: String
  , fy :: String
  , gradientTransform :: String
  , gradientUnits :: String
  , markerEnd :: String
  , markerMid :: String
  , markerStart :: String
  , mask :: String
  , offset :: String
  , opacity :: String
  , pathLength :: String
  , patternUnits :: String
  , pointerEvents :: String
  , points :: String
  , preserveAspectRatio :: String
  , r :: String
  , rx :: String
  , ry :: String
  , stopColor :: String
  , stopOpacity :: String
  , stroke :: String
  , strokeDasharray :: String
  , strokeDashoffset :: String
  , strokeLinecap :: String
  , strokeLinejoin :: String
  , strokeOpacity :: String
  , strokeWidth :: String
  , textAnchor :: String
  , transform :: String
  , vectorEffect :: String
  , viewBox :: String
  , visibility :: String
  , x :: String
  , x1 :: String
  , x2 :: String
  , y :: String
  , y1 :: String
  , y2 :: String
  )

a :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
a = typedElement @SVGAttributes svgNamespace "a"

altGlyph :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
altGlyph = typedElement @SVGAttributes svgNamespace "altGlyph"

altGlyphDef :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
altGlyphDef = typedElement @SVGAttributes svgNamespace "altGlyphDef"

altGlyphItem :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
altGlyphItem = typedElement @SVGAttributes svgNamespace "altGlyphItem"

animate :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
animate = typedElement @SVGAttributes svgNamespace "animate"

animateColor :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
animateColor = typedElement @SVGAttributes svgNamespace "animateColor"

animateMotion :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
animateMotion = typedElement @SVGAttributes svgNamespace "animateMotion"

animateTransform :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
animateTransform = typedElement @SVGAttributes svgNamespace "animateTransform"

circle :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
circle = typedElement @SVGAttributes svgNamespace "circle"

clipPath :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
clipPath = typedElement @SVGAttributes svgNamespace "clipPath"

colorProfile :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
colorProfile = typedElement @SVGAttributes svgNamespace "colorProfile"

cursor :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
cursor = typedElement @SVGAttributes svgNamespace "cursor"

defs :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
defs = typedElement @SVGAttributes svgNamespace "defs"

desc :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
desc = typedElement @SVGAttributes svgNamespace "desc"

ellipse :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
ellipse = typedElement @SVGAttributes svgNamespace "ellipse"

feBlend :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feBlend = typedElement @SVGAttributes svgNamespace "feBlend"

feColorMatrix :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feColorMatrix = typedElement @SVGAttributes svgNamespace "feColorMatrix"

feComponentTransfer :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feComponentTransfer = typedElement @SVGAttributes svgNamespace "feComponentTransfer"

feComposite :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feComposite = typedElement @SVGAttributes svgNamespace "feComposite"

feConvolveMatrix :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feConvolveMatrix = typedElement @SVGAttributes svgNamespace "feConvolveMatrix"

feDiffuseLighting :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feDiffuseLighting = typedElement @SVGAttributes svgNamespace "feDiffuseLighting"

feDisplacementMap :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feDisplacementMap = typedElement @SVGAttributes svgNamespace "feDisplacementMap"

feDistantLight :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feDistantLight = typedElement @SVGAttributes svgNamespace "feDistantLight"

feDropShadow :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feDropShadow = typedElement @SVGAttributes svgNamespace "feDropShadow"

feFlood :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feFlood = typedElement @SVGAttributes svgNamespace "feFlood"

feFuncA :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feFuncA = typedElement @SVGAttributes svgNamespace "feFuncA"

feFuncB :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feFuncB = typedElement @SVGAttributes svgNamespace "feFuncB"

feFuncG :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feFuncG = typedElement @SVGAttributes svgNamespace "feFuncG"

feFuncR :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feFuncR = typedElement @SVGAttributes svgNamespace "feFuncR"

feGaussianBlur :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feGaussianBlur = typedElement @SVGAttributes svgNamespace "feGaussianBlur"

feImage :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feImage = typedElement @SVGAttributes svgNamespace "feImage"

feMerge :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feMerge = typedElement @SVGAttributes svgNamespace "feMerge"

feMergeNode :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feMergeNode = typedElement @SVGAttributes svgNamespace "feMergeNode"

feMorphology :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feMorphology = typedElement @SVGAttributes svgNamespace "feMorphology"

feOffset :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feOffset = typedElement @SVGAttributes svgNamespace "feOffset"

fePointLight :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
fePointLight = typedElement @SVGAttributes svgNamespace "fePointLight"

feSpecularLighting :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feSpecularLighting = typedElement @SVGAttributes svgNamespace "feSpecularLighting"

feSpotLight :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feSpotLight = typedElement @SVGAttributes svgNamespace "feSpotLight"

feTile :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feTile = typedElement @SVGAttributes svgNamespace "feTile"

feTurbulence :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
feTurbulence = typedElement @SVGAttributes svgNamespace "feTurbulence"

filter :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
filter = typedElement @SVGAttributes svgNamespace "filter"

font :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
font = typedElement @SVGAttributes svgNamespace "font"

foreignObject :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
foreignObject = typedElement @SVGAttributes svgNamespace "foreignObject"

g :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
g = typedElement @SVGAttributes svgNamespace "g"

glyph :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
glyph = typedElement @SVGAttributes svgNamespace "glyph"

glyphRef :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
glyphRef = typedElement @SVGAttributes svgNamespace "glyphRef"

hkern :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
hkern = typedElement @SVGAttributes svgNamespace "hkern"

image :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
image = typedElement @SVGAttributes svgNamespace "image"

line :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
line = typedElement @SVGAttributes svgNamespace "line"

linearGradient :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
linearGradient = typedElement @SVGAttributes svgNamespace "linearGradient"

marker :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
marker = typedElement @SVGAttributes svgNamespace "marker"

mask :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
mask = typedElement @SVGAttributes svgNamespace "mask"

metadata :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
metadata = typedElement @SVGAttributes svgNamespace "metadata"

missingGlyph :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
missingGlyph = typedElement @SVGAttributes svgNamespace "missingGlyph"

mpath :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
mpath = typedElement @SVGAttributes svgNamespace "mpath"

path :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
path = typedElement @SVGAttributes svgNamespace "path"

pattern :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
pattern = typedElement @SVGAttributes svgNamespace "pattern"

polygon :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
polygon = typedElement @SVGAttributes svgNamespace "polygon"

polyline :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
polyline = typedElement @SVGAttributes svgNamespace "polyline"

radialGradient :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
radialGradient = typedElement @SVGAttributes svgNamespace "radialGradient"

rect :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
rect = typedElement @SVGAttributes svgNamespace "rect"

script :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
script = typedElement @SVGAttributes svgNamespace "script"

set :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
set = typedElement @SVGAttributes svgNamespace "set"

stop :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
stop = typedElement @SVGAttributes svgNamespace "stop"

style :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
style = typedElement @SVGAttributes svgNamespace "style"

svg :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
svg = typedElement @SVGAttributes svgNamespace "svg"

switch :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
switch = typedElement @SVGAttributes svgNamespace "switch"

symbol :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
symbol = typedElement @SVGAttributes svgNamespace "symbol"

text :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
text = typedElement @SVGAttributes svgNamespace "text"

textPath :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
textPath = typedElement @SVGAttributes svgNamespace "textPath"

title :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
title = typedElement @SVGAttributes svgNamespace "title"

tref :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
tref = typedElement @SVGAttributes svgNamespace "tref"

tspan :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
tspan = typedElement @SVGAttributes svgNamespace "tspan"

use :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
use = typedElement @SVGAttributes svgNamespace "use"

view :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
view = typedElement @SVGAttributes svgNamespace "view"

vkern :: forall props children. Props SVGAttributes props => Children children => Record props -> children -> JSX
vkern = typedElement @SVGAttributes svgNamespace "vkern"
