-- | SVG elements. Generated by `scripts/gen-dom.mjs`.
module Solid.DOM.SVG where

import DOM.HTML.Indexed as I
import Solid.Internal.View (JSX, Prop, elementWith, svgNamespace)
import Web.DOM.Element (Element)

type SVGAttributes = I.InteractiveEvents
  ( "$element" :: Element
  , class :: String
  , height :: String
  , href :: String
  , id :: String
  , lang :: String
  , style :: String
  , tabIndex :: Int
  , width :: String
  , clipPath :: String
  , clipRule :: String
  , cx :: String
  , cy :: String
  , d :: String
  , display :: String
  , dominantBaseline :: String
  , dx :: String
  , dy :: String
  , fill :: String
  , fillOpacity :: String
  , fillRule :: String
  , filter :: String
  , fontFamily :: String
  , fontSize :: String
  , fontWeight :: String
  , fx :: String
  , fy :: String
  , gradientTransform :: String
  , gradientUnits :: String
  , markerEnd :: String
  , markerMid :: String
  , markerStart :: String
  , mask :: String
  , offset :: String
  , opacity :: String
  , pathLength :: String
  , patternUnits :: String
  , pointerEvents :: String
  , points :: String
  , preserveAspectRatio :: String
  , r :: String
  , rx :: String
  , ry :: String
  , stopColor :: String
  , stopOpacity :: String
  , stroke :: String
  , strokeDasharray :: String
  , strokeDashoffset :: String
  , strokeLinecap :: String
  , strokeLinejoin :: String
  , strokeOpacity :: String
  , strokeWidth :: String
  , textAnchor :: String
  , transform :: String
  , vectorEffect :: String
  , viewBox :: String
  , visibility :: String
  , x :: String
  , x1 :: String
  , x2 :: String
  , y :: String
  , y1 :: String
  , y2 :: String
  )

a :: Array (Prop SVGAttributes) -> Array JSX -> JSX
a = elementWith svgNamespace "a"

a_ :: Array JSX -> JSX
a_ = elementWith svgNamespace "a" []

altGlyph :: Array (Prop SVGAttributes) -> Array JSX -> JSX
altGlyph = elementWith svgNamespace "altGlyph"

altGlyph_ :: Array JSX -> JSX
altGlyph_ = elementWith svgNamespace "altGlyph" []

altGlyphDef :: Array (Prop SVGAttributes) -> Array JSX -> JSX
altGlyphDef = elementWith svgNamespace "altGlyphDef"

altGlyphDef_ :: Array JSX -> JSX
altGlyphDef_ = elementWith svgNamespace "altGlyphDef" []

altGlyphItem :: Array (Prop SVGAttributes) -> Array JSX -> JSX
altGlyphItem = elementWith svgNamespace "altGlyphItem"

altGlyphItem_ :: Array JSX -> JSX
altGlyphItem_ = elementWith svgNamespace "altGlyphItem" []

animate :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animate = elementWith svgNamespace "animate"

animate_ :: Array JSX -> JSX
animate_ = elementWith svgNamespace "animate" []

animateColor :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animateColor = elementWith svgNamespace "animateColor"

animateColor_ :: Array JSX -> JSX
animateColor_ = elementWith svgNamespace "animateColor" []

animateMotion :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animateMotion = elementWith svgNamespace "animateMotion"

animateMotion_ :: Array JSX -> JSX
animateMotion_ = elementWith svgNamespace "animateMotion" []

animateTransform :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animateTransform = elementWith svgNamespace "animateTransform"

animateTransform_ :: Array JSX -> JSX
animateTransform_ = elementWith svgNamespace "animateTransform" []

circle :: Array (Prop SVGAttributes) -> Array JSX -> JSX
circle = elementWith svgNamespace "circle"

circle_ :: Array JSX -> JSX
circle_ = elementWith svgNamespace "circle" []

clipPath :: Array (Prop SVGAttributes) -> Array JSX -> JSX
clipPath = elementWith svgNamespace "clipPath"

clipPath_ :: Array JSX -> JSX
clipPath_ = elementWith svgNamespace "clipPath" []

colorProfile :: Array (Prop SVGAttributes) -> Array JSX -> JSX
colorProfile = elementWith svgNamespace "colorProfile"

colorProfile_ :: Array JSX -> JSX
colorProfile_ = elementWith svgNamespace "colorProfile" []

cursor :: Array (Prop SVGAttributes) -> Array JSX -> JSX
cursor = elementWith svgNamespace "cursor"

cursor_ :: Array JSX -> JSX
cursor_ = elementWith svgNamespace "cursor" []

defs :: Array (Prop SVGAttributes) -> Array JSX -> JSX
defs = elementWith svgNamespace "defs"

defs_ :: Array JSX -> JSX
defs_ = elementWith svgNamespace "defs" []

desc :: Array (Prop SVGAttributes) -> Array JSX -> JSX
desc = elementWith svgNamespace "desc"

desc_ :: Array JSX -> JSX
desc_ = elementWith svgNamespace "desc" []

ellipse :: Array (Prop SVGAttributes) -> Array JSX -> JSX
ellipse = elementWith svgNamespace "ellipse"

ellipse_ :: Array JSX -> JSX
ellipse_ = elementWith svgNamespace "ellipse" []

feBlend :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feBlend = elementWith svgNamespace "feBlend"

feBlend_ :: Array JSX -> JSX
feBlend_ = elementWith svgNamespace "feBlend" []

feColorMatrix :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feColorMatrix = elementWith svgNamespace "feColorMatrix"

feColorMatrix_ :: Array JSX -> JSX
feColorMatrix_ = elementWith svgNamespace "feColorMatrix" []

feComponentTransfer :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feComponentTransfer = elementWith svgNamespace "feComponentTransfer"

feComponentTransfer_ :: Array JSX -> JSX
feComponentTransfer_ = elementWith svgNamespace "feComponentTransfer" []

feComposite :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feComposite = elementWith svgNamespace "feComposite"

feComposite_ :: Array JSX -> JSX
feComposite_ = elementWith svgNamespace "feComposite" []

feConvolveMatrix :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feConvolveMatrix = elementWith svgNamespace "feConvolveMatrix"

feConvolveMatrix_ :: Array JSX -> JSX
feConvolveMatrix_ = elementWith svgNamespace "feConvolveMatrix" []

feDiffuseLighting :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDiffuseLighting = elementWith svgNamespace "feDiffuseLighting"

feDiffuseLighting_ :: Array JSX -> JSX
feDiffuseLighting_ = elementWith svgNamespace "feDiffuseLighting" []

feDisplacementMap :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDisplacementMap = elementWith svgNamespace "feDisplacementMap"

feDisplacementMap_ :: Array JSX -> JSX
feDisplacementMap_ = elementWith svgNamespace "feDisplacementMap" []

feDistantLight :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDistantLight = elementWith svgNamespace "feDistantLight"

feDistantLight_ :: Array JSX -> JSX
feDistantLight_ = elementWith svgNamespace "feDistantLight" []

feDropShadow :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDropShadow = elementWith svgNamespace "feDropShadow"

feDropShadow_ :: Array JSX -> JSX
feDropShadow_ = elementWith svgNamespace "feDropShadow" []

feFlood :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFlood = elementWith svgNamespace "feFlood"

feFlood_ :: Array JSX -> JSX
feFlood_ = elementWith svgNamespace "feFlood" []

feFuncA :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncA = elementWith svgNamespace "feFuncA"

feFuncA_ :: Array JSX -> JSX
feFuncA_ = elementWith svgNamespace "feFuncA" []

feFuncB :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncB = elementWith svgNamespace "feFuncB"

feFuncB_ :: Array JSX -> JSX
feFuncB_ = elementWith svgNamespace "feFuncB" []

feFuncG :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncG = elementWith svgNamespace "feFuncG"

feFuncG_ :: Array JSX -> JSX
feFuncG_ = elementWith svgNamespace "feFuncG" []

feFuncR :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncR = elementWith svgNamespace "feFuncR"

feFuncR_ :: Array JSX -> JSX
feFuncR_ = elementWith svgNamespace "feFuncR" []

feGaussianBlur :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feGaussianBlur = elementWith svgNamespace "feGaussianBlur"

feGaussianBlur_ :: Array JSX -> JSX
feGaussianBlur_ = elementWith svgNamespace "feGaussianBlur" []

feImage :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feImage = elementWith svgNamespace "feImage"

feImage_ :: Array JSX -> JSX
feImage_ = elementWith svgNamespace "feImage" []

feMerge :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feMerge = elementWith svgNamespace "feMerge"

feMerge_ :: Array JSX -> JSX
feMerge_ = elementWith svgNamespace "feMerge" []

feMergeNode :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feMergeNode = elementWith svgNamespace "feMergeNode"

feMergeNode_ :: Array JSX -> JSX
feMergeNode_ = elementWith svgNamespace "feMergeNode" []

feMorphology :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feMorphology = elementWith svgNamespace "feMorphology"

feMorphology_ :: Array JSX -> JSX
feMorphology_ = elementWith svgNamespace "feMorphology" []

feOffset :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feOffset = elementWith svgNamespace "feOffset"

feOffset_ :: Array JSX -> JSX
feOffset_ = elementWith svgNamespace "feOffset" []

fePointLight :: Array (Prop SVGAttributes) -> Array JSX -> JSX
fePointLight = elementWith svgNamespace "fePointLight"

fePointLight_ :: Array JSX -> JSX
fePointLight_ = elementWith svgNamespace "fePointLight" []

feSpecularLighting :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feSpecularLighting = elementWith svgNamespace "feSpecularLighting"

feSpecularLighting_ :: Array JSX -> JSX
feSpecularLighting_ = elementWith svgNamespace "feSpecularLighting" []

feSpotLight :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feSpotLight = elementWith svgNamespace "feSpotLight"

feSpotLight_ :: Array JSX -> JSX
feSpotLight_ = elementWith svgNamespace "feSpotLight" []

feTile :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feTile = elementWith svgNamespace "feTile"

feTile_ :: Array JSX -> JSX
feTile_ = elementWith svgNamespace "feTile" []

feTurbulence :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feTurbulence = elementWith svgNamespace "feTurbulence"

feTurbulence_ :: Array JSX -> JSX
feTurbulence_ = elementWith svgNamespace "feTurbulence" []

filter :: Array (Prop SVGAttributes) -> Array JSX -> JSX
filter = elementWith svgNamespace "filter"

filter_ :: Array JSX -> JSX
filter_ = elementWith svgNamespace "filter" []

font :: Array (Prop SVGAttributes) -> Array JSX -> JSX
font = elementWith svgNamespace "font"

font_ :: Array JSX -> JSX
font_ = elementWith svgNamespace "font" []

foreignObject :: Array (Prop SVGAttributes) -> Array JSX -> JSX
foreignObject = elementWith svgNamespace "foreignObject"

foreignObject_ :: Array JSX -> JSX
foreignObject_ = elementWith svgNamespace "foreignObject" []

g :: Array (Prop SVGAttributes) -> Array JSX -> JSX
g = elementWith svgNamespace "g"

g_ :: Array JSX -> JSX
g_ = elementWith svgNamespace "g" []

glyph :: Array (Prop SVGAttributes) -> Array JSX -> JSX
glyph = elementWith svgNamespace "glyph"

glyph_ :: Array JSX -> JSX
glyph_ = elementWith svgNamespace "glyph" []

glyphRef :: Array (Prop SVGAttributes) -> Array JSX -> JSX
glyphRef = elementWith svgNamespace "glyphRef"

glyphRef_ :: Array JSX -> JSX
glyphRef_ = elementWith svgNamespace "glyphRef" []

hkern :: Array (Prop SVGAttributes) -> Array JSX -> JSX
hkern = elementWith svgNamespace "hkern"

hkern_ :: Array JSX -> JSX
hkern_ = elementWith svgNamespace "hkern" []

image :: Array (Prop SVGAttributes) -> Array JSX -> JSX
image = elementWith svgNamespace "image"

image_ :: Array JSX -> JSX
image_ = elementWith svgNamespace "image" []

line :: Array (Prop SVGAttributes) -> Array JSX -> JSX
line = elementWith svgNamespace "line"

line_ :: Array JSX -> JSX
line_ = elementWith svgNamespace "line" []

linearGradient :: Array (Prop SVGAttributes) -> Array JSX -> JSX
linearGradient = elementWith svgNamespace "linearGradient"

linearGradient_ :: Array JSX -> JSX
linearGradient_ = elementWith svgNamespace "linearGradient" []

marker :: Array (Prop SVGAttributes) -> Array JSX -> JSX
marker = elementWith svgNamespace "marker"

marker_ :: Array JSX -> JSX
marker_ = elementWith svgNamespace "marker" []

mask :: Array (Prop SVGAttributes) -> Array JSX -> JSX
mask = elementWith svgNamespace "mask"

mask_ :: Array JSX -> JSX
mask_ = elementWith svgNamespace "mask" []

metadata :: Array (Prop SVGAttributes) -> Array JSX -> JSX
metadata = elementWith svgNamespace "metadata"

metadata_ :: Array JSX -> JSX
metadata_ = elementWith svgNamespace "metadata" []

missingGlyph :: Array (Prop SVGAttributes) -> Array JSX -> JSX
missingGlyph = elementWith svgNamespace "missingGlyph"

missingGlyph_ :: Array JSX -> JSX
missingGlyph_ = elementWith svgNamespace "missingGlyph" []

mpath :: Array (Prop SVGAttributes) -> Array JSX -> JSX
mpath = elementWith svgNamespace "mpath"

mpath_ :: Array JSX -> JSX
mpath_ = elementWith svgNamespace "mpath" []

path :: Array (Prop SVGAttributes) -> Array JSX -> JSX
path = elementWith svgNamespace "path"

path_ :: Array JSX -> JSX
path_ = elementWith svgNamespace "path" []

pattern :: Array (Prop SVGAttributes) -> Array JSX -> JSX
pattern = elementWith svgNamespace "pattern"

pattern_ :: Array JSX -> JSX
pattern_ = elementWith svgNamespace "pattern" []

polygon :: Array (Prop SVGAttributes) -> Array JSX -> JSX
polygon = elementWith svgNamespace "polygon"

polygon_ :: Array JSX -> JSX
polygon_ = elementWith svgNamespace "polygon" []

polyline :: Array (Prop SVGAttributes) -> Array JSX -> JSX
polyline = elementWith svgNamespace "polyline"

polyline_ :: Array JSX -> JSX
polyline_ = elementWith svgNamespace "polyline" []

radialGradient :: Array (Prop SVGAttributes) -> Array JSX -> JSX
radialGradient = elementWith svgNamespace "radialGradient"

radialGradient_ :: Array JSX -> JSX
radialGradient_ = elementWith svgNamespace "radialGradient" []

rect :: Array (Prop SVGAttributes) -> Array JSX -> JSX
rect = elementWith svgNamespace "rect"

rect_ :: Array JSX -> JSX
rect_ = elementWith svgNamespace "rect" []

script :: Array (Prop SVGAttributes) -> Array JSX -> JSX
script = elementWith svgNamespace "script"

script_ :: Array JSX -> JSX
script_ = elementWith svgNamespace "script" []

set :: Array (Prop SVGAttributes) -> Array JSX -> JSX
set = elementWith svgNamespace "set"

set_ :: Array JSX -> JSX
set_ = elementWith svgNamespace "set" []

stop :: Array (Prop SVGAttributes) -> Array JSX -> JSX
stop = elementWith svgNamespace "stop"

stop_ :: Array JSX -> JSX
stop_ = elementWith svgNamespace "stop" []

style :: Array (Prop SVGAttributes) -> Array JSX -> JSX
style = elementWith svgNamespace "style"

style_ :: Array JSX -> JSX
style_ = elementWith svgNamespace "style" []

svg :: Array (Prop SVGAttributes) -> Array JSX -> JSX
svg = elementWith svgNamespace "svg"

svg_ :: Array JSX -> JSX
svg_ = elementWith svgNamespace "svg" []

switch :: Array (Prop SVGAttributes) -> Array JSX -> JSX
switch = elementWith svgNamespace "switch"

switch_ :: Array JSX -> JSX
switch_ = elementWith svgNamespace "switch" []

symbol :: Array (Prop SVGAttributes) -> Array JSX -> JSX
symbol = elementWith svgNamespace "symbol"

symbol_ :: Array JSX -> JSX
symbol_ = elementWith svgNamespace "symbol" []

text :: Array (Prop SVGAttributes) -> Array JSX -> JSX
text = elementWith svgNamespace "text"

text_ :: Array JSX -> JSX
text_ = elementWith svgNamespace "text" []

textPath :: Array (Prop SVGAttributes) -> Array JSX -> JSX
textPath = elementWith svgNamespace "textPath"

textPath_ :: Array JSX -> JSX
textPath_ = elementWith svgNamespace "textPath" []

title :: Array (Prop SVGAttributes) -> Array JSX -> JSX
title = elementWith svgNamespace "title"

title_ :: Array JSX -> JSX
title_ = elementWith svgNamespace "title" []

tref :: Array (Prop SVGAttributes) -> Array JSX -> JSX
tref = elementWith svgNamespace "tref"

tref_ :: Array JSX -> JSX
tref_ = elementWith svgNamespace "tref" []

tspan :: Array (Prop SVGAttributes) -> Array JSX -> JSX
tspan = elementWith svgNamespace "tspan"

tspan_ :: Array JSX -> JSX
tspan_ = elementWith svgNamespace "tspan" []

use :: Array (Prop SVGAttributes) -> Array JSX -> JSX
use = elementWith svgNamespace "use"

use_ :: Array JSX -> JSX
use_ = elementWith svgNamespace "use" []

view :: Array (Prop SVGAttributes) -> Array JSX -> JSX
view = elementWith svgNamespace "view"

view_ :: Array JSX -> JSX
view_ = elementWith svgNamespace "view" []

vkern :: Array (Prop SVGAttributes) -> Array JSX -> JSX
vkern = elementWith svgNamespace "vkern"

vkern_ :: Array JSX -> JSX
vkern_ = elementWith svgNamespace "vkern" []
