-- | SVG elements. Generated by `scripts/gen-dom.mjs`.
module Solid.DOM.SVG where

import DOM.HTML.Indexed as I
import Solid.Internal.View (JSX, Namespace(..), Prop, elementWith)

type SVGAttributes = I.InteractiveEvents
  ( class :: String
  , height :: String
  , href :: String
  , id :: String
  , lang :: String
  , style :: String
  , tabIndex :: Int
  , width :: String
  , clipPath :: String
  , clipRule :: String
  , cx :: String
  , cy :: String
  , d :: String
  , display :: String
  , dominantBaseline :: String
  , dx :: String
  , dy :: String
  , fill :: String
  , fillOpacity :: String
  , fillRule :: String
  , filter :: String
  , fontFamily :: String
  , fontSize :: String
  , fontWeight :: String
  , fx :: String
  , fy :: String
  , gradientTransform :: String
  , gradientUnits :: String
  , markerEnd :: String
  , markerMid :: String
  , markerStart :: String
  , mask :: String
  , offset :: String
  , opacity :: String
  , pathLength :: String
  , patternUnits :: String
  , pointerEvents :: String
  , points :: String
  , preserveAspectRatio :: String
  , r :: String
  , rx :: String
  , ry :: String
  , stopColor :: String
  , stopOpacity :: String
  , stroke :: String
  , strokeDasharray :: String
  , strokeDashoffset :: String
  , strokeLinecap :: String
  , strokeLinejoin :: String
  , strokeOpacity :: String
  , strokeWidth :: String
  , textAnchor :: String
  , transform :: String
  , vectorEffect :: String
  , viewBox :: String
  , visibility :: String
  , x :: String
  , x1 :: String
  , x2 :: String
  , y :: String
  , y1 :: String
  , y2 :: String
  )

a :: Array (Prop SVGAttributes) -> Array JSX -> JSX
a = elementWith SvgNamespace "a"

a_ :: Array JSX -> JSX
a_ = elementWith SvgNamespace "a" []

altGlyph :: Array (Prop SVGAttributes) -> Array JSX -> JSX
altGlyph = elementWith SvgNamespace "altGlyph"

altGlyph_ :: Array JSX -> JSX
altGlyph_ = elementWith SvgNamespace "altGlyph" []

altGlyphDef :: Array (Prop SVGAttributes) -> Array JSX -> JSX
altGlyphDef = elementWith SvgNamespace "altGlyphDef"

altGlyphDef_ :: Array JSX -> JSX
altGlyphDef_ = elementWith SvgNamespace "altGlyphDef" []

altGlyphItem :: Array (Prop SVGAttributes) -> Array JSX -> JSX
altGlyphItem = elementWith SvgNamespace "altGlyphItem"

altGlyphItem_ :: Array JSX -> JSX
altGlyphItem_ = elementWith SvgNamespace "altGlyphItem" []

animate :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animate = elementWith SvgNamespace "animate"

animate_ :: Array JSX -> JSX
animate_ = elementWith SvgNamespace "animate" []

animateColor :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animateColor = elementWith SvgNamespace "animateColor"

animateColor_ :: Array JSX -> JSX
animateColor_ = elementWith SvgNamespace "animateColor" []

animateMotion :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animateMotion = elementWith SvgNamespace "animateMotion"

animateMotion_ :: Array JSX -> JSX
animateMotion_ = elementWith SvgNamespace "animateMotion" []

animateTransform :: Array (Prop SVGAttributes) -> Array JSX -> JSX
animateTransform = elementWith SvgNamespace "animateTransform"

animateTransform_ :: Array JSX -> JSX
animateTransform_ = elementWith SvgNamespace "animateTransform" []

circle :: Array (Prop SVGAttributes) -> Array JSX -> JSX
circle = elementWith SvgNamespace "circle"

circle_ :: Array JSX -> JSX
circle_ = elementWith SvgNamespace "circle" []

clipPath :: Array (Prop SVGAttributes) -> Array JSX -> JSX
clipPath = elementWith SvgNamespace "clipPath"

clipPath_ :: Array JSX -> JSX
clipPath_ = elementWith SvgNamespace "clipPath" []

colorProfile :: Array (Prop SVGAttributes) -> Array JSX -> JSX
colorProfile = elementWith SvgNamespace "colorProfile"

colorProfile_ :: Array JSX -> JSX
colorProfile_ = elementWith SvgNamespace "colorProfile" []

cursor :: Array (Prop SVGAttributes) -> Array JSX -> JSX
cursor = elementWith SvgNamespace "cursor"

cursor_ :: Array JSX -> JSX
cursor_ = elementWith SvgNamespace "cursor" []

defs :: Array (Prop SVGAttributes) -> Array JSX -> JSX
defs = elementWith SvgNamespace "defs"

defs_ :: Array JSX -> JSX
defs_ = elementWith SvgNamespace "defs" []

desc :: Array (Prop SVGAttributes) -> Array JSX -> JSX
desc = elementWith SvgNamespace "desc"

desc_ :: Array JSX -> JSX
desc_ = elementWith SvgNamespace "desc" []

ellipse :: Array (Prop SVGAttributes) -> Array JSX -> JSX
ellipse = elementWith SvgNamespace "ellipse"

ellipse_ :: Array JSX -> JSX
ellipse_ = elementWith SvgNamespace "ellipse" []

feBlend :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feBlend = elementWith SvgNamespace "feBlend"

feBlend_ :: Array JSX -> JSX
feBlend_ = elementWith SvgNamespace "feBlend" []

feColorMatrix :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feColorMatrix = elementWith SvgNamespace "feColorMatrix"

feColorMatrix_ :: Array JSX -> JSX
feColorMatrix_ = elementWith SvgNamespace "feColorMatrix" []

feComponentTransfer :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feComponentTransfer = elementWith SvgNamespace "feComponentTransfer"

feComponentTransfer_ :: Array JSX -> JSX
feComponentTransfer_ = elementWith SvgNamespace "feComponentTransfer" []

feComposite :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feComposite = elementWith SvgNamespace "feComposite"

feComposite_ :: Array JSX -> JSX
feComposite_ = elementWith SvgNamespace "feComposite" []

feConvolveMatrix :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feConvolveMatrix = elementWith SvgNamespace "feConvolveMatrix"

feConvolveMatrix_ :: Array JSX -> JSX
feConvolveMatrix_ = elementWith SvgNamespace "feConvolveMatrix" []

feDiffuseLighting :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDiffuseLighting = elementWith SvgNamespace "feDiffuseLighting"

feDiffuseLighting_ :: Array JSX -> JSX
feDiffuseLighting_ = elementWith SvgNamespace "feDiffuseLighting" []

feDisplacementMap :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDisplacementMap = elementWith SvgNamespace "feDisplacementMap"

feDisplacementMap_ :: Array JSX -> JSX
feDisplacementMap_ = elementWith SvgNamespace "feDisplacementMap" []

feDistantLight :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDistantLight = elementWith SvgNamespace "feDistantLight"

feDistantLight_ :: Array JSX -> JSX
feDistantLight_ = elementWith SvgNamespace "feDistantLight" []

feDropShadow :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feDropShadow = elementWith SvgNamespace "feDropShadow"

feDropShadow_ :: Array JSX -> JSX
feDropShadow_ = elementWith SvgNamespace "feDropShadow" []

feFlood :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFlood = elementWith SvgNamespace "feFlood"

feFlood_ :: Array JSX -> JSX
feFlood_ = elementWith SvgNamespace "feFlood" []

feFuncA :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncA = elementWith SvgNamespace "feFuncA"

feFuncA_ :: Array JSX -> JSX
feFuncA_ = elementWith SvgNamespace "feFuncA" []

feFuncB :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncB = elementWith SvgNamespace "feFuncB"

feFuncB_ :: Array JSX -> JSX
feFuncB_ = elementWith SvgNamespace "feFuncB" []

feFuncG :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncG = elementWith SvgNamespace "feFuncG"

feFuncG_ :: Array JSX -> JSX
feFuncG_ = elementWith SvgNamespace "feFuncG" []

feFuncR :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feFuncR = elementWith SvgNamespace "feFuncR"

feFuncR_ :: Array JSX -> JSX
feFuncR_ = elementWith SvgNamespace "feFuncR" []

feGaussianBlur :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feGaussianBlur = elementWith SvgNamespace "feGaussianBlur"

feGaussianBlur_ :: Array JSX -> JSX
feGaussianBlur_ = elementWith SvgNamespace "feGaussianBlur" []

feImage :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feImage = elementWith SvgNamespace "feImage"

feImage_ :: Array JSX -> JSX
feImage_ = elementWith SvgNamespace "feImage" []

feMerge :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feMerge = elementWith SvgNamespace "feMerge"

feMerge_ :: Array JSX -> JSX
feMerge_ = elementWith SvgNamespace "feMerge" []

feMergeNode :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feMergeNode = elementWith SvgNamespace "feMergeNode"

feMergeNode_ :: Array JSX -> JSX
feMergeNode_ = elementWith SvgNamespace "feMergeNode" []

feMorphology :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feMorphology = elementWith SvgNamespace "feMorphology"

feMorphology_ :: Array JSX -> JSX
feMorphology_ = elementWith SvgNamespace "feMorphology" []

feOffset :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feOffset = elementWith SvgNamespace "feOffset"

feOffset_ :: Array JSX -> JSX
feOffset_ = elementWith SvgNamespace "feOffset" []

fePointLight :: Array (Prop SVGAttributes) -> Array JSX -> JSX
fePointLight = elementWith SvgNamespace "fePointLight"

fePointLight_ :: Array JSX -> JSX
fePointLight_ = elementWith SvgNamespace "fePointLight" []

feSpecularLighting :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feSpecularLighting = elementWith SvgNamespace "feSpecularLighting"

feSpecularLighting_ :: Array JSX -> JSX
feSpecularLighting_ = elementWith SvgNamespace "feSpecularLighting" []

feSpotLight :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feSpotLight = elementWith SvgNamespace "feSpotLight"

feSpotLight_ :: Array JSX -> JSX
feSpotLight_ = elementWith SvgNamespace "feSpotLight" []

feTile :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feTile = elementWith SvgNamespace "feTile"

feTile_ :: Array JSX -> JSX
feTile_ = elementWith SvgNamespace "feTile" []

feTurbulence :: Array (Prop SVGAttributes) -> Array JSX -> JSX
feTurbulence = elementWith SvgNamespace "feTurbulence"

feTurbulence_ :: Array JSX -> JSX
feTurbulence_ = elementWith SvgNamespace "feTurbulence" []

filter :: Array (Prop SVGAttributes) -> Array JSX -> JSX
filter = elementWith SvgNamespace "filter"

filter_ :: Array JSX -> JSX
filter_ = elementWith SvgNamespace "filter" []

font :: Array (Prop SVGAttributes) -> Array JSX -> JSX
font = elementWith SvgNamespace "font"

font_ :: Array JSX -> JSX
font_ = elementWith SvgNamespace "font" []

foreignObject :: Array (Prop SVGAttributes) -> Array JSX -> JSX
foreignObject = elementWith SvgNamespace "foreignObject"

foreignObject_ :: Array JSX -> JSX
foreignObject_ = elementWith SvgNamespace "foreignObject" []

g :: Array (Prop SVGAttributes) -> Array JSX -> JSX
g = elementWith SvgNamespace "g"

g_ :: Array JSX -> JSX
g_ = elementWith SvgNamespace "g" []

glyph :: Array (Prop SVGAttributes) -> Array JSX -> JSX
glyph = elementWith SvgNamespace "glyph"

glyph_ :: Array JSX -> JSX
glyph_ = elementWith SvgNamespace "glyph" []

glyphRef :: Array (Prop SVGAttributes) -> Array JSX -> JSX
glyphRef = elementWith SvgNamespace "glyphRef"

glyphRef_ :: Array JSX -> JSX
glyphRef_ = elementWith SvgNamespace "glyphRef" []

hkern :: Array (Prop SVGAttributes) -> Array JSX -> JSX
hkern = elementWith SvgNamespace "hkern"

hkern_ :: Array JSX -> JSX
hkern_ = elementWith SvgNamespace "hkern" []

image :: Array (Prop SVGAttributes) -> Array JSX -> JSX
image = elementWith SvgNamespace "image"

image_ :: Array JSX -> JSX
image_ = elementWith SvgNamespace "image" []

line :: Array (Prop SVGAttributes) -> Array JSX -> JSX
line = elementWith SvgNamespace "line"

line_ :: Array JSX -> JSX
line_ = elementWith SvgNamespace "line" []

linearGradient :: Array (Prop SVGAttributes) -> Array JSX -> JSX
linearGradient = elementWith SvgNamespace "linearGradient"

linearGradient_ :: Array JSX -> JSX
linearGradient_ = elementWith SvgNamespace "linearGradient" []

marker :: Array (Prop SVGAttributes) -> Array JSX -> JSX
marker = elementWith SvgNamespace "marker"

marker_ :: Array JSX -> JSX
marker_ = elementWith SvgNamespace "marker" []

mask :: Array (Prop SVGAttributes) -> Array JSX -> JSX
mask = elementWith SvgNamespace "mask"

mask_ :: Array JSX -> JSX
mask_ = elementWith SvgNamespace "mask" []

metadata :: Array (Prop SVGAttributes) -> Array JSX -> JSX
metadata = elementWith SvgNamespace "metadata"

metadata_ :: Array JSX -> JSX
metadata_ = elementWith SvgNamespace "metadata" []

missingGlyph :: Array (Prop SVGAttributes) -> Array JSX -> JSX
missingGlyph = elementWith SvgNamespace "missingGlyph"

missingGlyph_ :: Array JSX -> JSX
missingGlyph_ = elementWith SvgNamespace "missingGlyph" []

mpath :: Array (Prop SVGAttributes) -> Array JSX -> JSX
mpath = elementWith SvgNamespace "mpath"

mpath_ :: Array JSX -> JSX
mpath_ = elementWith SvgNamespace "mpath" []

path :: Array (Prop SVGAttributes) -> Array JSX -> JSX
path = elementWith SvgNamespace "path"

path_ :: Array JSX -> JSX
path_ = elementWith SvgNamespace "path" []

pattern :: Array (Prop SVGAttributes) -> Array JSX -> JSX
pattern = elementWith SvgNamespace "pattern"

pattern_ :: Array JSX -> JSX
pattern_ = elementWith SvgNamespace "pattern" []

polygon :: Array (Prop SVGAttributes) -> Array JSX -> JSX
polygon = elementWith SvgNamespace "polygon"

polygon_ :: Array JSX -> JSX
polygon_ = elementWith SvgNamespace "polygon" []

polyline :: Array (Prop SVGAttributes) -> Array JSX -> JSX
polyline = elementWith SvgNamespace "polyline"

polyline_ :: Array JSX -> JSX
polyline_ = elementWith SvgNamespace "polyline" []

radialGradient :: Array (Prop SVGAttributes) -> Array JSX -> JSX
radialGradient = elementWith SvgNamespace "radialGradient"

radialGradient_ :: Array JSX -> JSX
radialGradient_ = elementWith SvgNamespace "radialGradient" []

rect :: Array (Prop SVGAttributes) -> Array JSX -> JSX
rect = elementWith SvgNamespace "rect"

rect_ :: Array JSX -> JSX
rect_ = elementWith SvgNamespace "rect" []

script :: Array (Prop SVGAttributes) -> Array JSX -> JSX
script = elementWith SvgNamespace "script"

script_ :: Array JSX -> JSX
script_ = elementWith SvgNamespace "script" []

set :: Array (Prop SVGAttributes) -> Array JSX -> JSX
set = elementWith SvgNamespace "set"

set_ :: Array JSX -> JSX
set_ = elementWith SvgNamespace "set" []

stop :: Array (Prop SVGAttributes) -> Array JSX -> JSX
stop = elementWith SvgNamespace "stop"

stop_ :: Array JSX -> JSX
stop_ = elementWith SvgNamespace "stop" []

style :: Array (Prop SVGAttributes) -> Array JSX -> JSX
style = elementWith SvgNamespace "style"

style_ :: Array JSX -> JSX
style_ = elementWith SvgNamespace "style" []

svg :: Array (Prop SVGAttributes) -> Array JSX -> JSX
svg = elementWith SvgNamespace "svg"

svg_ :: Array JSX -> JSX
svg_ = elementWith SvgNamespace "svg" []

switch :: Array (Prop SVGAttributes) -> Array JSX -> JSX
switch = elementWith SvgNamespace "switch"

switch_ :: Array JSX -> JSX
switch_ = elementWith SvgNamespace "switch" []

symbol :: Array (Prop SVGAttributes) -> Array JSX -> JSX
symbol = elementWith SvgNamespace "symbol"

symbol_ :: Array JSX -> JSX
symbol_ = elementWith SvgNamespace "symbol" []

text :: Array (Prop SVGAttributes) -> Array JSX -> JSX
text = elementWith SvgNamespace "text"

text_ :: Array JSX -> JSX
text_ = elementWith SvgNamespace "text" []

textPath :: Array (Prop SVGAttributes) -> Array JSX -> JSX
textPath = elementWith SvgNamespace "textPath"

textPath_ :: Array JSX -> JSX
textPath_ = elementWith SvgNamespace "textPath" []

title :: Array (Prop SVGAttributes) -> Array JSX -> JSX
title = elementWith SvgNamespace "title"

title_ :: Array JSX -> JSX
title_ = elementWith SvgNamespace "title" []

tref :: Array (Prop SVGAttributes) -> Array JSX -> JSX
tref = elementWith SvgNamespace "tref"

tref_ :: Array JSX -> JSX
tref_ = elementWith SvgNamespace "tref" []

tspan :: Array (Prop SVGAttributes) -> Array JSX -> JSX
tspan = elementWith SvgNamespace "tspan"

tspan_ :: Array JSX -> JSX
tspan_ = elementWith SvgNamespace "tspan" []

use :: Array (Prop SVGAttributes) -> Array JSX -> JSX
use = elementWith SvgNamespace "use"

use_ :: Array JSX -> JSX
use_ = elementWith SvgNamespace "use" []

view :: Array (Prop SVGAttributes) -> Array JSX -> JSX
view = elementWith SvgNamespace "view"

view_ :: Array JSX -> JSX
view_ = elementWith SvgNamespace "view" []

vkern :: Array (Prop SVGAttributes) -> Array JSX -> JSX
vkern = elementWith SvgNamespace "vkern"

vkern_ :: Array JSX -> JSX
vkern_ = elementWith SvgNamespace "vkern" []
